/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
window.dhtmlx||(dhtmlx=function(a){for(var c in a)dhtmlx[c]=a[c];return dhtmlx});
dhtmlx.extend_api=function(a,c,b){var e=window[a];if(e)window[a]=function(b){if(b&&typeof b=="object"&&!b.tagName){var a=e.apply(this,c._init?c._init(b):arguments),f;for(f in dhtmlx)if(c[f])this[c[f]](dhtmlx[f]);for(f in b)if(c[f])this[c[f]](b[f]);else f.indexOf("on")==0&&this.attachEvent(f,b[f])}else a=e.apply(this,arguments);c._patch&&c._patch(this);return a||this},window[a].prototype=e.prototype,b&&dhtmlXHeir(window[a].prototype,b)};
dhtmlxAjax={get:function(a,c){var b=new dtmlXMLLoaderObject(!0);b.async=arguments.length<3;b.waitCall=c;b.loadXML(a);return b},post:function(a,c,b){var e=new dtmlXMLLoaderObject(!0);e.async=arguments.length<4;e.waitCall=b;e.loadXML(a,!0,c);return e},getSync:function(a){return this.get(a,null,!0)},postSync:function(a,c){return this.post(a,c,null,!0)}};
function dtmlXMLLoaderObject(a,c,b,e){this.xmlDoc="";this.async=typeof b!="undefined"?b:!0;this.onloadAction=a||null;this.mainObject=c||null;this.waitCall=null;this.rSeed=e||!1;return this}dtmlXMLLoaderObject.count=0;
dtmlXMLLoaderObject.prototype.waitLoadFunction=function(a){var c=!0;return this.check=function(){if(a&&a.onloadAction!=null&&(!a.xmlDoc.readyState||a.xmlDoc.readyState==4)&&c){c=!1;dtmlXMLLoaderObject.count++;if(typeof a.onloadAction=="function")a.onloadAction(a.mainObject,null,null,null,a);if(a.waitCall)a.waitCall.call(this,a),a.waitCall=null}}};
dtmlXMLLoaderObject.prototype.getXMLTopNode=function(a,c){if(this.xmlDoc.responseXML){var b=this.xmlDoc.responseXML.getElementsByTagName(a);b.length==0&&a.indexOf(":")!=-1&&(b=this.xmlDoc.responseXML.getElementsByTagName(a.split(":")[1]));var e=b[0]}else e=this.xmlDoc.documentElement;if(e)return this._retry=!1,e;if(!this._retry)return this._retry=!0,c=this.xmlDoc,this.loadXMLString(this.xmlDoc.responseText.replace(/^[\s]+/,""),!0),this.getXMLTopNode(a,c);dhtmlxError.throwError("LoadXML","Incorrect XML",
[c||this.xmlDoc,this.mainObject]);return document.createElement("DIV")};dtmlXMLLoaderObject.prototype.loadXMLString=function(a,c){if(_isIE)this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async=this.async,this.xmlDoc.onreadystatechange=function(){},this.xmlDoc.loadXML(a);else{var b=new DOMParser;this.xmlDoc=b.parseFromString(a,"text/xml")}if(!c){if(this.onloadAction)this.onloadAction(this.mainObject,null,null,null,this);if(this.waitCall)this.waitCall(),this.waitCall=null}};
dtmlXMLLoaderObject.prototype.loadXML=function(a,c,b,e){this.rSeed&&(a+=(a.indexOf("?")!=-1?"&":"?")+"a_dhx_rSeed="+(new Date).valueOf());this.filePath=a;this.xmlDoc=!_isIE&&window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");if(this.async)this.xmlDoc.onreadystatechange=new this.waitLoadFunction(this);this.xmlDoc.open(c?"POST":"GET",a,this.async);e?(this.xmlDoc.setRequestHeader("User-Agent","dhtmlxRPC v0.1 ("+navigator.userAgent+")"),this.xmlDoc.setRequestHeader("Content-type",
"text/xml")):c&&this.xmlDoc.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.xmlDoc.setRequestHeader("X-Requested-With","XMLHttpRequest");this.xmlDoc.send(b);this.async||(new this.waitLoadFunction(this))()};
dtmlXMLLoaderObject.prototype.destructor=function(){return this.setXSLParamValue=this.getXMLTopNode=this.xmlNodeToJSON=this.doSerialization=this.loadXMLString=this.loadXML=this.doXSLTransToString=this.doXSLTransToObject=this.doXPathOpera=this.doXPath=this.xmlDoc=this.mainObject=this.onloadAction=this.filePath=this.rSeed=this.async=this._retry=this._getAllNamedChilds=this._filterXPath=null};
dtmlXMLLoaderObject.prototype.xmlNodeToJSON=function(a){for(var c={},b=0;b<a.attributes.length;b++)c[a.attributes[b].name]=a.attributes[b].value;c._tagvalue=a.firstChild?a.firstChild.nodeValue:"";for(b=0;b<a.childNodes.length;b++){var e=a.childNodes[b].tagName;e&&(c[e]||(c[e]=[]),c[e].push(this.xmlNodeToJSON(a.childNodes[b])))}return c};function callerFunction(a,c){return this.handler=function(b){if(!b)b=window.event;a(b,c);return!0}}function getAbsoluteLeft(a){return getOffset(a).left}
function getAbsoluteTop(a){return getOffset(a).top}function getOffsetSum(a){for(var c=0,b=0;a;)c+=parseInt(a.offsetTop),b+=parseInt(a.offsetLeft),a=a.offsetParent;return{top:c,left:b}}
function getOffsetRect(a){var c=a.getBoundingClientRect(),b=document.body,e=document.documentElement,d=window.pageYOffset||e.scrollTop||b.scrollTop,i=window.pageXOffset||e.scrollLeft||b.scrollLeft,f=e.clientTop||b.clientTop||0,g=e.clientLeft||b.clientLeft||0,h=c.top+d-f,j=c.left+i-g;return{top:Math.round(h),left:Math.round(j)}}function getOffset(a){return a.getBoundingClientRect?getOffsetRect(a):getOffsetSum(a)}
function convertStringToBoolean(a){typeof a=="string"&&(a=a.toLowerCase());switch(a){case "1":case "true":case "yes":case "y":case 1:case !0:return!0;default:return!1}}function getUrlSymbol(a){return a.indexOf("?")!=-1?"&":"?"}function dhtmlDragAndDropObject(){if(window.dhtmlDragAndDrop)return window.dhtmlDragAndDrop;this.dragStartObject=this.dragStartNode=this.dragNode=this.lastLanding=0;this.tempDOMM=this.tempDOMU=null;this.waitDrag=0;window.dhtmlDragAndDrop=this;return this}
dhtmlDragAndDropObject.prototype.removeDraggableItem=function(a){a.onmousedown=null;a.dragStarter=null;a.dragLanding=null};dhtmlDragAndDropObject.prototype.addDraggableItem=function(a,c){a.onmousedown=this.preCreateDragCopy;a.dragStarter=c;this.addDragLanding(a,c)};dhtmlDragAndDropObject.prototype.addDragLanding=function(a,c){a.dragLanding=c};
dhtmlDragAndDropObject.prototype.preCreateDragCopy=function(a){if(!((a||window.event)&&(a||event).button==2)){if(window.dhtmlDragAndDrop.waitDrag)return window.dhtmlDragAndDrop.waitDrag=0,document.body.onmouseup=window.dhtmlDragAndDrop.tempDOMU,document.body.onmousemove=window.dhtmlDragAndDrop.tempDOMM,!1;window.dhtmlDragAndDrop.dragNode&&window.dhtmlDragAndDrop.stopDrag(a);window.dhtmlDragAndDrop.waitDrag=1;window.dhtmlDragAndDrop.tempDOMU=document.body.onmouseup;window.dhtmlDragAndDrop.tempDOMM=
document.body.onmousemove;window.dhtmlDragAndDrop.dragStartNode=this;window.dhtmlDragAndDrop.dragStartObject=this.dragStarter;document.body.onmouseup=window.dhtmlDragAndDrop.preCreateDragCopy;document.body.onmousemove=window.dhtmlDragAndDrop.callDrag;window.dhtmlDragAndDrop.downtime=(new Date).valueOf();a&&a.preventDefault&&a.preventDefault();return!1}};
dhtmlDragAndDropObject.prototype.callDrag=function(a){if(!a)a=window.event;dragger=window.dhtmlDragAndDrop;if(!((new Date).valueOf()-dragger.downtime<100)){if(!dragger.dragNode)if(dragger.waitDrag){dragger.dragNode=dragger.dragStartObject._createDragNode(dragger.dragStartNode,a);if(!dragger.dragNode)return dragger.stopDrag();dragger.dragNode.onselectstart=function(){return!1};dragger.gldragNode=dragger.dragNode;document.body.appendChild(dragger.dragNode);document.body.onmouseup=dragger.stopDrag;dragger.waitDrag=
0;dragger.dragNode.pWindow=window;dragger.initFrameRoute()}else return dragger.stopDrag(a,!0);if(dragger.dragNode.parentNode!=window.document.body&&dragger.gldragNode){var c=dragger.gldragNode;if(dragger.gldragNode.old)c=dragger.gldragNode.old;c.parentNode.removeChild(c);var b=dragger.dragNode.pWindow;c.pWindow&&c.pWindow.dhtmlDragAndDrop.lastLanding&&c.pWindow.dhtmlDragAndDrop.lastLanding.dragLanding._dragOut(c.pWindow.dhtmlDragAndDrop.lastLanding);if(_isIE){var e=document.createElement("Div");e.innerHTML=
dragger.dragNode.outerHTML;dragger.dragNode=e.childNodes[0]}else dragger.dragNode=dragger.dragNode.cloneNode(!0);dragger.dragNode.pWindow=window;dragger.gldragNode.old=dragger.dragNode;document.body.appendChild(dragger.dragNode);b.dhtmlDragAndDrop.dragNode=dragger.dragNode}dragger.dragNode.style.left=a.clientX+15+(dragger.fx?dragger.fx*-1:0)+(document.body.scrollLeft||document.documentElement.scrollLeft)+"px";dragger.dragNode.style.top=a.clientY+3+(dragger.fy?dragger.fy*-1:0)+(document.body.scrollTop||
document.documentElement.scrollTop)+"px";var d=a.srcElement?a.srcElement:a.target;dragger.checkLanding(d,a)}};dhtmlDragAndDropObject.prototype.calculateFramePosition=function(a){if(window.name){for(var c=parent.frames[window.name].frameElement.offsetParent,b=0,e=0;c;)b+=c.offsetLeft,e+=c.offsetTop,c=c.offsetParent;if(parent.dhtmlDragAndDrop){var d=parent.dhtmlDragAndDrop.calculateFramePosition(1);b+=d.split("_")[0]*1;e+=d.split("_")[1]*1}if(a)return b+"_"+e;else this.fx=b;this.fy=e}return"0_0"};
dhtmlDragAndDropObject.prototype.checkLanding=function(a,c){a&&a.dragLanding?(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding),this.lastLanding=a,this.lastLanding=this.lastLanding.dragLanding._dragIn(this.lastLanding,this.dragStartNode,c.clientX,c.clientY,c),this.lastLanding_scr=_isIE?c.srcElement:c.target):a&&a.tagName!="BODY"?this.checkLanding(a.parentNode,c):(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding,c.clientX,c.clientY,c),this.lastLanding=
0,this._onNotFound&&this._onNotFound())};
dhtmlDragAndDropObject.prototype.stopDrag=function(a,c){dragger=window.dhtmlDragAndDrop;if(!c){dragger.stopFrameRoute();var b=dragger.lastLanding;dragger.lastLanding=null;b&&b.dragLanding._drag(dragger.dragStartNode,dragger.dragStartObject,b,_isIE?event.srcElement:a.target)}dragger.lastLanding=null;dragger.dragNode&&dragger.dragNode.parentNode==document.body&&dragger.dragNode.parentNode.removeChild(dragger.dragNode);dragger.dragNode=0;dragger.gldragNode=0;dragger.fx=0;dragger.fy=0;dragger.dragStartNode=
0;dragger.dragStartObject=0;document.body.onmouseup=dragger.tempDOMU;document.body.onmousemove=dragger.tempDOMM;dragger.tempDOMU=null;dragger.tempDOMM=null;dragger.waitDrag=0};dhtmlDragAndDropObject.prototype.stopFrameRoute=function(a){a&&window.dhtmlDragAndDrop.stopDrag(1,1);for(var c=0;c<window.frames.length;c++)try{window.frames[c]!=a&&window.frames[c].dhtmlDragAndDrop&&window.frames[c].dhtmlDragAndDrop.stopFrameRoute(window)}catch(b){}try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=a&&parent.dhtmlDragAndDrop.stopFrameRoute(window)}catch(e){}};
dhtmlDragAndDropObject.prototype.initFrameRoute=function(a,c){if(a)window.dhtmlDragAndDrop.preCreateDragCopy(),window.dhtmlDragAndDrop.dragStartNode=a.dhtmlDragAndDrop.dragStartNode,window.dhtmlDragAndDrop.dragStartObject=a.dhtmlDragAndDrop.dragStartObject,window.dhtmlDragAndDrop.dragNode=a.dhtmlDragAndDrop.dragNode,window.dhtmlDragAndDrop.gldragNode=a.dhtmlDragAndDrop.dragNode,window.document.body.onmouseup=window.dhtmlDragAndDrop.stopDrag,window.waitDrag=0,!_isIE&&c&&(!_isFF||_FFrv<1.8)&&window.dhtmlDragAndDrop.calculateFramePosition();
try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=a&&parent.dhtmlDragAndDrop.initFrameRoute(window)}catch(b){}for(var e=0;e<window.frames.length;e++)try{window.frames[e]!=a&&window.frames[e].dhtmlDragAndDrop&&window.frames[e].dhtmlDragAndDrop.initFrameRoute(window,!a||c?1:0)}catch(d){}};_OperaRv=_KHTMLrv=_FFrv=_isChrome=_isMacOS=_isKHTML=_isOpera=_isIE=_isFF=!1;navigator.userAgent.indexOf("Macintosh")!=-1&&(_isMacOS=!0);navigator.userAgent.toLowerCase().indexOf("chrome")>-1&&(_isChrome=!0);
if(navigator.userAgent.indexOf("Safari")!=-1||navigator.userAgent.indexOf("Konqueror")!=-1)_KHTMLrv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Safari")+7,5)),_KHTMLrv>525?(_isFF=!0,_FFrv=1.9):_isKHTML=!0;else if(navigator.userAgent.indexOf("Opera")!=-1)_isOpera=!0,_OperaRv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Opera")+6,3));else if(navigator.appName.indexOf("Microsoft")!=-1){if(_isIE=!0,(navigator.appVersion.indexOf("MSIE 8.0")!=-1||navigator.appVersion.indexOf("MSIE 9.0")!=
-1||navigator.appVersion.indexOf("MSIE 10.0")!=-1)&&document.compatMode!="BackCompat")_isIE=8}else _isFF=!0,_FFrv=parseFloat(navigator.userAgent.split("rv:")[1]);
dtmlXMLLoaderObject.prototype.doXPath=function(a,c,b,e){if(_isKHTML||!_isIE&&!window.XPathResult)return this.doXPathOpera(a,c);if(_isIE)return c||(c=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML),c||dhtmlxError.throwError("LoadXML","Incorrect XML",[c||this.xmlDoc,this.mainObject]),b!=null&&c.setProperty("SelectionNamespaces","xmlns:xsl='"+b+"'"),e=="single"?c.selectSingleNode(a):c.selectNodes(a)||[];else{var d=c;c||(c=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML);c||dhtmlxError.throwError("LoadXML",
"Incorrect XML",[c||this.xmlDoc,this.mainObject]);c.nodeName.indexOf("document")!=-1?d=c:(d=c,c=c.ownerDocument);var i=XPathResult.ANY_TYPE;if(e=="single")i=XPathResult.FIRST_ORDERED_NODE_TYPE;var f=[],g=c.evaluate(a,d,function(){return b},i,null);if(i==XPathResult.FIRST_ORDERED_NODE_TYPE)return g.singleNodeValue;for(var h=g.iterateNext();h;)f[f.length]=h,h=g.iterateNext();return f}};function y(){if(!this.catches)this.catches=[];return this}y.prototype.catchError=function(a,c){this.catches[a]=c};
y.prototype.throwError=function(a,c,b){if(this.catches[a])return this.catches[a](a,c,b);if(this.catches.ALL)return this.catches.ALL(a,c,b);alert("Error type: "+a+"\nDescription: "+c);return null};window.dhtmlxError=new y;
dtmlXMLLoaderObject.prototype.doXPathOpera=function(a,c){var b=a.replace(/[\/]+/gi,"/").split("/"),e=null,d=1;if(!b.length)return[];if(b[0]==".")e=[c];else if(b[0]=="")e=(this.xmlDoc.responseXML||this.xmlDoc).getElementsByTagName(b[d].replace(/\[[^\]]*\]/g,"")),d++;else return[];for(;d<b.length;d++)e=this._getAllNamedChilds(e,b[d]);b[d-1].indexOf("[")!=-1&&(e=this._filterXPath(e,b[d-1]));return e};
dtmlXMLLoaderObject.prototype._filterXPath=function(a,c){for(var b=[],c=c.replace(/[^\[]*\[\@/g,"").replace(/[\[\]\@]*/g,""),e=0;e<a.length;e++)a[e].getAttribute(c)&&(b[b.length]=a[e]);return b};
dtmlXMLLoaderObject.prototype._getAllNamedChilds=function(a,c){var b=[];_isKHTML&&(c=c.toUpperCase());for(var e=0;e<a.length;e++)for(var d=0;d<a[e].childNodes.length;d++)_isKHTML?a[e].childNodes[d].tagName&&a[e].childNodes[d].tagName.toUpperCase()==c&&(b[b.length]=a[e].childNodes[d]):a[e].childNodes[d].tagName==c&&(b[b.length]=a[e].childNodes[d]);return b};function dhtmlXHeir(a,c){for(var b in c)typeof c[b]=="function"&&(a[b]=c[b]);return a}
function dhtmlxEvent(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent&&a.attachEvent("on"+c,b)}dtmlXMLLoaderObject.prototype.xslDoc=null;dtmlXMLLoaderObject.prototype.setXSLParamValue=function(a,c,b){if(!b)b=this.xslDoc;if(b.responseXML)b=b.responseXML;var e=this.doXPath("/xsl:stylesheet/xsl:variable[@name='"+a+"']",b,"http://www.w3.org/1999/XSL/Transform","single");if(e!=null)e.firstChild.nodeValue=c};
dtmlXMLLoaderObject.prototype.doXSLTransToObject=function(a,c){if(!a)a=this.xslDoc;if(a.responseXML)a=a.responseXML;if(!c)c=this.xmlDoc;if(c.responseXML)c=c.responseXML;if(_isIE){e=new ActiveXObject("Msxml2.DOMDocument.3.0");try{c.transformNodeToObject(a,e)}catch(b){e=c.transformNode(a)}}else{if(!this.XSLProcessor)this.XSLProcessor=new XSLTProcessor,this.XSLProcessor.importStylesheet(a);var e=this.XSLProcessor.transformToDocument(c)}return e};
dtmlXMLLoaderObject.prototype.doXSLTransToString=function(a,c){var b=this.doXSLTransToObject(a,c);return typeof b=="string"?b:this.doSerialization(b)};dtmlXMLLoaderObject.prototype.doSerialization=function(a){if(!a)a=this.xmlDoc;if(a.responseXML)a=a.responseXML;if(_isIE)return a.xml;else{var c=new XMLSerializer;return c.serializeToString(a)}};
dhtmlxEventable=function(a){a.attachEvent=function(a,b,e){a="ev_"+a.toLowerCase();this[a]||(this[a]=new this.eventCatcher(e||this));return a+":"+this[a].addEvent(b)};a.callEvent=function(a,b){a="ev_"+a.toLowerCase();return this[a]?this[a].apply(this,b):!0};a.checkEvent=function(a){return!!this["ev_"+a.toLowerCase()]};a.eventCatcher=function(a){var b=[],e=function(){for(var e=!0,i=0;i<b.length;i++)if(b[i]!=null)var f=b[i].apply(a,arguments),e=e&&f;return e};e.addEvent=function(a){typeof a!="function"&&
(a=eval(a));return a?b.push(a)-1:!1};e.removeEvent=function(a){b[a]=null};return e};a.detachEvent=function(a){if(a!=!1){var b=a.split(":");this[b[0]].removeEvent(b[1])}};a.detachAllEvents=function(){for(var a in this)a.indexOf("ev_")==0&&delete this[a]};a=null};if(!window.dhtmlx)window.dhtmlx={};
(function(){function a(a,e){var d=a.callback;b(!1);a.box.parentNode.removeChild(a.box);k=a.box=null;d&&d(e)}function c(b){if(k){var b=b||event,e=b.which||event.keyCode;dhtmlx.message.keyboard&&((e==13||e==32)&&a(k,!0),e==27&&a(k,!1));b.preventDefault&&b.preventDefault();return!(b.cancelBubble=!0)}}function b(a){if(!b.cover)b.cover=document.createElement("DIV"),b.cover.onkeydown=c,b.cover.className="dhx_modal_cover",document.body.appendChild(b.cover);var e=document.body.scrollHeight;b.cover.style.display=
a?"inline-block":"none"}function e(b,a){var e="dhtmlx_"+b.toLowerCase().replace(/ /g,"_")+"_button";return"<div class='dhtmlx_popup_button "+e+"' result='"+a+"' ><div>"+b+"</div></div>"}function d(b){if(!m.area)m.area=document.createElement("DIV"),m.area.className="dhtmlx_message_area",m.area.style[m.position]="5px",document.body.appendChild(m.area);m.hide(b.id);var a=document.createElement("DIV");a.innerHTML="<div>"+b.text+"</div>";a.className="dhtmlx-info dhtmlx-"+b.type;a.onclick=function(){m.hide(b.id);
b=null};m.position=="bottom"&&m.area.firstChild?m.area.insertBefore(a,m.area.firstChild):m.area.appendChild(a);b.expire>0&&(m.timers[b.id]=window.setTimeout(function(){m.hide(b.id)},b.expire));m.pull[b.id]=a;a=null;return b.id}function i(b,d,i){var f=document.createElement("DIV");f.className=" dhtmlx_modal_box dhtmlx-"+b.type;f.setAttribute("dhxbox",1);var c="";if(b.width)f.style.width=b.width;if(b.height)f.style.height=b.height;b.title&&(c+='<div class="dhtmlx_popup_title">'+b.title+"</div>");c+=
'<div class="dhtmlx_popup_text"><span>'+(b.content?"":b.text)+'</span></div><div  class="dhtmlx_popup_controls">';d&&(c+=e(b.ok||"OK",!0));i&&(c+=e(b.cancel||"Cancel",!1));if(b.buttons)for(var g=0;g<b.buttons.length;g++)c+=e(b.buttons[g],g);c+="</div>";f.innerHTML=c;if(b.content){var h=b.content;typeof h=="string"&&(h=document.getElementById(h));if(h.style.display=="none")h.style.display="";f.childNodes[b.title?1:0].appendChild(h)}f.onclick=function(e){var e=e||event,d=e.target||e.srcElement;if(!d.className)d=
d.parentNode;d.className.split(" ")[0]=="dhtmlx_popup_button"&&(result=d.getAttribute("result"),result=result=="true"||(result=="false"?!1:result),a(b,result))};b.box=f;if(d||i)k=b;return f}function f(a,e,d){var f=a.tagName?a:i(a,e,d);a.hidden||b(!0);document.body.appendChild(f);var g=Math.abs(Math.floor(((window.innerWidth||document.documentElement.offsetWidth)-f.offsetWidth)/2)),h=Math.abs(Math.floor(((window.innerHeight||document.documentElement.offsetHeight)-f.offsetHeight)/2));f.style.top=a.position==
"top"?"-3px":h+"px";f.style.left=g+"px";f.onkeydown=c;f.focus();a.hidden&&dhtmlx.modalbox.hide(f);return f}function g(b){return f(b,!0,!1)}function h(b){return f(b,!0,!0)}function j(b){return f(b)}function n(b,a,e){typeof b!="object"&&(typeof a=="function"&&(e=a,a=""),b={text:b,type:a,callback:e});return b}function l(b,a,e,d){typeof b!="object"&&(b={text:b,type:a,expire:e,id:d});b.id=b.id||m.uid();b.expire=b.expire||m.expire;return b}var k=null;document.attachEvent?document.attachEvent("onkeydown",
c):document.addEventListener("keydown",c,!0);dhtmlx.alert=function(){text=n.apply(this,arguments);text.type=text.type||"confirm";return g(text)};dhtmlx.confirm=function(){text=n.apply(this,arguments);text.type=text.type||"alert";return h(text)};dhtmlx.modalbox=function(){text=n.apply(this,arguments);text.type=text.type||"alert";return j(text)};dhtmlx.modalbox.hide=function(a){for(;a&&a.getAttribute&&!a.getAttribute("dhxbox");)a=a.parentNode;a&&(a.parentNode.removeChild(a),b(!1))};var m=dhtmlx.message=
function(b,a,e,i){b=l.apply(this,arguments);b.type=b.type||"info";var f=b.type.split("-")[0];switch(f){case "alert":return g(b);case "confirm":return h(b);case "modalbox":return j(b);default:return d(b)}};m.seed=(new Date).valueOf();m.uid=function(){return m.seed++};m.expire=4E3;m.keyboard=!0;m.position="top";m.pull={};m.timers={};m.hideAll=function(){for(var b in m.pull)m.hide(b)};m.hide=function(b){var a=m.pull[b];a&&a.parentNode&&(window.setTimeout(function(){a.parentNode.removeChild(a);a=null},
2E3),a.className+=" hidden",m.timers[b]&&window.clearTimeout(m.timers[b]),delete m.pull[b])}})();
function dataProcessor(a){this.serverProcessor=a;this.action_param="!nativeeditor_status";this.object=null;this.updatedRows=[];this.autoUpdate=!0;this.updateMode="cell";this._tMode="GET";this.post_delim="_";this._waitMode=0;this._in_progress={};this._invalid={};this.mandatoryFields=[];this.messages=[];this.styles={updated:"font-weight:bold;",inserted:"font-weight:bold;",deleted:"text-decoration : line-through;",invalid:"background-color:FFE0E0;",invalid_cell:"border-bottom:2px solid red;",error:"color:red;",
clear:"font-weight:normal;text-decoration:none;"};this.enableUTFencoding(!0);dhtmlxEventable(this);return this}
dataProcessor.prototype={setTransactionMode:function(a,c){this._tMode=a;this._tSend=c},escape:function(a){return this._utf?encodeURIComponent(a):escape(a)},enableUTFencoding:function(a){this._utf=convertStringToBoolean(a)},setDataColumns:function(a){this._columns=typeof a=="string"?a.split(","):a},getSyncState:function(){return!this.updatedRows.length},enableDataNames:function(a){this._endnm=convertStringToBoolean(a)},enablePartialDataSend:function(a){this._changed=convertStringToBoolean(a)},setUpdateMode:function(a,
c){this.autoUpdate=a=="cell";this.updateMode=a;this.dnd=c},ignore:function(a,c){this._silent_mode=!0;a.call(c||window);this._silent_mode=!1},setUpdated:function(a,c,b){if(!this._silent_mode){var e=this.findRow(a),b=b||"updated",d=this.obj.getUserData(a,this.action_param);d&&b=="updated"&&(b=d);c?(this.set_invalid(a,!1),this.updatedRows[e]=a,this.obj.setUserData(a,this.action_param,b),this._in_progress[a]&&(this._in_progress[a]="wait")):this.is_invalid(a)||(this.updatedRows.splice(e,1),this.obj.setUserData(a,
this.action_param,""));c||this._clearUpdateFlag(a);this.markRow(a,c,b);c&&this.autoUpdate&&this.sendData(a)}},_clearUpdateFlag:function(){},markRow:function(a,c,b){var e="",d=this.is_invalid(a);d&&(e=this.styles[d],c=!0);if(this.callEvent("onRowMark",[a,c,b,d])&&(e=this.styles[c?b:"clear"]+e,this.obj[this._methods[0]](a,e),d&&d.details)){e+=this.styles[d+"_cell"];for(var i=0;i<d.details.length;i++)if(d.details[i])this.obj[this._methods[1]](a,i,e)}},getState:function(a){return this.obj.getUserData(a,
this.action_param)},is_invalid:function(a){return this._invalid[a]},set_invalid:function(a,c,b){b&&(c={value:c,details:b,toString:function(){return this.value.toString()}});this._invalid[a]=c},checkBeforeUpdate:function(){return!0},sendData:function(a){if(!this._waitMode||!(this.obj.mytype=="tree"||this.obj._h2)){this.obj.editStop&&this.obj.editStop();if(typeof a=="undefined"||this._tSend)return this.sendAllData();if(this._in_progress[a])return!1;this.messages=[];if(!this.checkBeforeUpdate(a)&&this.callEvent("onValidatationError",
[a,this.messages]))return!1;this._beforeSendData(this._getRowData(a),a)}},_beforeSendData:function(a,c){if(!this.callEvent("onBeforeUpdate",[c,this.getState(c),a]))return!1;this._sendData(a,c)},serialize:function(a,c){if(typeof a=="string")return a;if(typeof c!="undefined")return this.serialize_one(a,"");else{var b=[],e=[],d;for(d in a)a.hasOwnProperty(d)&&(b.push(this.serialize_one(a[d],d+this.post_delim)),e.push(d));b.push("ids="+this.escape(e.join(",")));dhtmlx.security_key&&b.push("dhx_security="+
dhtmlx.security_key);return b.join("&")}},serialize_one:function(a,c){if(typeof a=="string")return a;var b=[],e;for(e in a)a.hasOwnProperty(e)&&b.push(this.escape((c||"")+e)+"="+this.escape(a[e]));return b.join("&")},_sendData:function(a,c){if(a){if(!this.callEvent("onBeforeDataSending",c?[c,this.getState(c),a]:[null,null,a]))return!1;c&&(this._in_progress[c]=(new Date).valueOf());var b=new dtmlXMLLoaderObject(this.afterUpdate,this,!0),e=this.serverProcessor+(this._user?getUrlSymbol(this.serverProcessor)+
["dhx_user="+this._user,"dhx_version="+this.obj.getUserData(0,"version")].join("&"):"");this._tMode!="POST"?b.loadXML(e+(e.indexOf("?")!=-1?"&":"?")+this.serialize(a,c)):b.loadXML(e,!0,this.serialize(a,c));this._waitMode++}},sendAllData:function(){if(this.updatedRows.length){this.messages=[];for(var a=!0,c=0;c<this.updatedRows.length;c++)a&=this.checkBeforeUpdate(this.updatedRows[c]);if(!a&&!this.callEvent("onValidatationError",["",this.messages]))return!1;if(this._tSend)this._sendData(this._getAllData());
else for(c=0;c<this.updatedRows.length;c++)if(!this._in_progress[this.updatedRows[c]]&&!this.is_invalid(this.updatedRows[c])&&(this._beforeSendData(this._getRowData(this.updatedRows[c]),this.updatedRows[c]),this._waitMode&&(this.obj.mytype=="tree"||this.obj._h2)))break}},_getAllData:function(){for(var a={},c=!1,b=0;b<this.updatedRows.length;b++){var e=this.updatedRows[b];!this._in_progress[e]&&!this.is_invalid(e)&&this.callEvent("onBeforeUpdate",[e,this.getState(e)])&&(a[e]=this._getRowData(e,e+this.post_delim),
c=!0,this._in_progress[e]=(new Date).valueOf())}return c?a:null},setVerificator:function(a,c){this.mandatoryFields[a]=c||function(b){return b!=""}},clearVerificator:function(a){this.mandatoryFields[a]=!1},findRow:function(a){for(var c=0,c=0;c<this.updatedRows.length;c++)if(a==this.updatedRows[c])break;return c},defineAction:function(a,c){if(!this._uActions)this._uActions=[];this._uActions[a]=c},afterUpdateCallback:function(a,c,b,e){var d=a,i=b!="error"&&b!="invalid";i||this.set_invalid(a,b);if(this._uActions&&
this._uActions[b]&&!this._uActions[b](e))return delete this._in_progress[d];this._in_progress[d]!="wait"&&this.setUpdated(a,!1);var f=a;switch(b){case "update":case "updated":case "inserted":case "insert":c!=a&&(this.obj[this._methods[2]](a,c),a=c);break;case "delete":case "deleted":return this.obj.setUserData(a,this.action_param,"true_deleted"),this.obj[this._methods[3]](a),delete this._in_progress[d],this.callEvent("onAfterUpdate",[a,b,c,e])}this._in_progress[d]!="wait"?(i&&this.obj.setUserData(a,
this.action_param,""),delete this._in_progress[d]):(delete this._in_progress[d],this.setUpdated(c,!0,this.obj.getUserData(a,this.action_param)));this.callEvent("onAfterUpdate",[a,b,c,e])},afterUpdate:function(a,c,b,e,d){d.getXMLTopNode("data");if(d.xmlDoc.responseXML){for(var i=d.doXPath("//data/action"),f=0;f<i.length;f++){var g=i[f],h=g.getAttribute("type"),j=g.getAttribute("sid"),n=g.getAttribute("tid");a.afterUpdateCallback(j,n,h,g)}a.finalizeUpdate()}},finalizeUpdate:function(){this._waitMode&&
this._waitMode--;(this.obj.mytype=="tree"||this.obj._h2)&&this.updatedRows.length&&this.sendData();this.callEvent("onAfterUpdateFinish",[]);this.updatedRows.length||this.callEvent("onFullSync",[])},init:function(a){this.obj=a;this.obj._dp_init&&this.obj._dp_init(this)},setOnAfterUpdate:function(a){this.attachEvent("onAfterUpdate",a)},enableDebug:function(){},setOnBeforeUpdateHandler:function(a){this.attachEvent("onBeforeDataSending",a)},setAutoUpdate:function(a,c){a=a||2E3;this._user=c||(new Date).valueOf();
this._need_update=!1;this._loader=null;this._update_busy=!1;this.attachEvent("onAfterUpdate",function(b,a,i,f){this.afterAutoUpdate(b,a,i,f)});this.attachEvent("onFullSync",function(){this.fullSync()});var b=this;window.setInterval(function(){b.loadUpdate()},a)},afterAutoUpdate:function(a,c){return c=="collision"?(this._need_update=!0,!1):!0},fullSync:function(){if(this._need_update==!0)this._need_update=!1,this.loadUpdate();return!0},getUpdates:function(a,c){if(this._update_busy)return!1;else this._update_busy=
!0;this._loader=this._loader||new dtmlXMLLoaderObject(!0);this._loader.async=!0;this._loader.waitCall=c;this._loader.loadXML(a)},_v:function(a){return a.firstChild?a.firstChild.nodeValue:""},_a:function(a){for(var c=[],b=0;b<a.length;b++)c[b]=this._v(a[b]);return c},loadUpdate:function(){var a=this,c=this.obj.getUserData(0,"version"),b=this.serverProcessor+getUrlSymbol(this.serverProcessor)+["dhx_user="+this._user,"dhx_version="+c].join("&"),b=b.replace("editing=true&","");this.getUpdates(b,function(){var b=
a._loader.doXPath("//userdata");a.obj.setUserData(0,"version",a._v(b[0]));var d=a._loader.doXPath("//update");if(d.length){a._silent_mode=!0;for(var i=0;i<d.length;i++){var f=d[i].getAttribute("status"),c=d[i].getAttribute("id"),h=d[i].getAttribute("parent");switch(f){case "inserted":a.callEvent("insertCallback",[d[i],c,h]);break;case "updated":a.callEvent("updateCallback",[d[i],c,h]);break;case "deleted":a.callEvent("deleteCallback",[d[i],c,h])}}a._silent_mode=!1}a._update_busy=!1;a=null})}};
if(window.dhtmlXGridObject)dhtmlXGridObject.prototype._init_point_connector=dhtmlXGridObject.prototype._init_point,dhtmlXGridObject.prototype._init_point=function(){var a=function(b){b=b.replace(/(\?|\&)connector[^\f]*/g,"");return b+(b.indexOf("?")!=-1?"&":"?")+"connector=true"+(this.hdr.rows.length>0?"&dhx_no_header=1":"")},c=function(b){return a.call(this,b)+(this._connector_sorting||"")+(this._connector_filter||"")},b=function(b,a,e){this._connector_sorting="&dhx_sort["+a+"]="+e;return c.call(this,
b)},e=function(b,a,e){for(var g=0;g<a.length;g++)a[g]="dhx_filter["+a[g]+"]="+encodeURIComponent(e[g]);this._connector_filter="&"+a.join("&");return c.call(this,b)};this.attachEvent("onCollectValues",function(b){return this._con_f_used[b]?typeof this._con_f_used[b]=="object"?this._con_f_used[b]:!1:!0});this.attachEvent("onDynXLS",function(){this.xmlFileUrl=c.call(this,this.xmlFileUrl);return!0});this.attachEvent("onBeforeSorting",function(a,e,f){if(e=="connector"){var c=this;this.clearAndLoad(b.call(this,
this.xmlFileUrl,a,f),function(){c.setSortImgState(!0,a,f)});return!1}return!0});this.attachEvent("onFilterStart",function(b,a){return this._con_f_used.length?(this.clearAndLoad(e.call(this,this.xmlFileUrl,b,a)),!1):!0});this.attachEvent("onXLE",function(){});this._init_point_connector&&this._init_point_connector()},dhtmlXGridObject.prototype._con_f_used=[],dhtmlXGridObject.prototype._in_header_connector_text_filter=function(a,c){this._con_f_used[c]||(this._con_f_used[c]=1);return this._in_header_text_filter(a,
c)},dhtmlXGridObject.prototype._in_header_connector_select_filter=function(a,c){this._con_f_used[c]||(this._con_f_used[c]=2);return this._in_header_select_filter(a,c)},dhtmlXGridObject.prototype.load_connector=dhtmlXGridObject.prototype.load,dhtmlXGridObject.prototype.load=function(a,c,b){if(!this._colls_loaded&&this.cellType){for(var e=[],d=0;d<this.cellType.length;d++)(this.cellType[d].indexOf("co")==0||this._con_f_used[d]==2)&&e.push(d);e.length&&(arguments[0]+=(arguments[0].indexOf("?")!=-1?"&":
"?")+"connector=true&dhx_colls="+e.join(","))}return this.load_connector.apply(this,arguments)},dhtmlXGridObject.prototype._parseHead_connector=dhtmlXGridObject.prototype._parseHead,dhtmlXGridObject.prototype._parseHead=function(a,c,b){this._parseHead_connector.apply(this,arguments);if(!this._colls_loaded){for(var e=this.xmlLoader.doXPath("./coll_options",arguments[0]),d=0;d<e.length;d++){var i=e[d].getAttribute("for"),f=[],g=null;this.cellType[i]=="combo"&&(g=this.getColumnCombo(i));this.cellType[i].indexOf("co")==
0&&(g=this.getCombo(i));for(var h=this.xmlLoader.doXPath("./item",e[d]),j=0;j<h.length;j++){var n=h[j].getAttribute("value");if(g){var l=h[j].getAttribute("label")||n;g.addOption?g.addOption([[n,l]]):g.put(n,l);f[f.length]=l}else f[f.length]=n}this._con_f_used[i*1]&&(this._con_f_used[i*1]=f)}this._colls_loaded=!0}};
if(window.dataProcessor)dataProcessor.prototype.init_original=dataProcessor.prototype.init,dataProcessor.prototype.init=function(a){this.init_original(a);a._dataprocessor=this;this.setTransactionMode("POST",!0);this.serverProcessor+=(this.serverProcessor.indexOf("?")!=-1?"&":"?")+"editing=true"};dhtmlxError.catchError("LoadXML",function(a,c,b){b[0].status!=0&&alert(b[0].responseText)});window.Scheduler={_seed:0};Scheduler.plugin=function(a){this._schedulerPlugins.push(a);a(window.scheduler)};
Scheduler._schedulerPlugins=[];
Scheduler.getSchedulerInstance=function(){var a={version:"3.5"};dhtmlxEventable(a);a.init=function(b,e,d){e=e||new Date;d=d||"week";a.date.init();this._obj=typeof b=="string"?document.getElementById(b):b;this._els=[];this._scroll=!0;this._quirks=_isIE&&document.compatMode=="BackCompat";this._quirks7=_isIE&&navigator.appVersion.indexOf("MSIE 8")==-1;this.get_elements();this.init_templates();this.set_actions();dhtmlxEvent(window,"resize",function(){window.clearTimeout(a._resize_timer);a._resize_timer=
window.setTimeout(function(){a.callEvent("onSchedulerResize",[])&&(a.update_view(),a.callEvent("onAfterSchedulerResize",[]))},100)});this.set_sizes();a.callEvent("onSchedulerReady",[]);this.setCurrentView(e,d)};a.xy={nav_height:22,min_event_height:40,scale_width:50,bar_height:20,scroll_width:18,scale_height:20,month_scale_height:20,menu_width:25,margin_top:0,margin_left:0,editor_width:140,lightbox_additional_height:50};a.keys={edit_save:13,edit_cancel:27};a.set_sizes=function(){var b=this._x=this._obj.clientWidth-
this.xy.margin_left,a=this._y=this._obj.clientHeight-this.xy.margin_top,d=this._table_view?0:this.xy.scale_width+this.xy.scroll_width,i=this._table_view?-1:this.xy.scale_width;this.set_xy(this._els.dhx_cal_navline[0],b,this.xy.nav_height,0,0);this.set_xy(this._els.dhx_cal_header[0],b-d,this.xy.scale_height,i,this.xy.nav_height+(this._quirks?-1:1));var f=this._els.dhx_cal_navline[0].offsetHeight;if(f>0)this.xy.nav_height=f;var c=this.xy.scale_height+this.xy.nav_height+(this._quirks?-2:0);this.set_xy(this._els.dhx_cal_data[0],
b,a-(c+2),0,c+2)};a.set_xy=function(b,a,d,i,f){b.style.width=Math.max(0,a)+"px";b.style.height=Math.max(0,d)+"px";if(arguments.length>3)b.style.left=i+"px",b.style.top=f+"px"};a.get_elements=function(){for(var b=this._obj.getElementsByTagName("DIV"),e=0;e<b.length;e++){var d=b[e].className;d&&(d=d.split(" ")[0]);this._els[d]||(this._els[d]=[]);this._els[d].push(b[e]);var i=a.locale.labels[b[e].getAttribute("name")||d];if(i)b[e].innerHTML=i}};a.set_actions=function(){for(var b in this._els)if(this._click[b])for(var e=
0;e<this._els[b].length;e++)this._els[b][e].onclick=a._click[b];this._obj.onselectstart=function(){return!1};this._obj.onmousemove=function(b){a._on_mouse_move(b||event)};this._obj.onmousedown=function(b){a._on_mouse_down(b||event)};this._obj.onmouseup=function(b){a._on_mouse_up(b||event)};this._obj.ondblclick=function(b){a._on_dbl_click(b||event)};this._obj.oncontextmenu=function(b){var e=b||event,f=e.target||e.srcElement,c=a.callEvent("onContextMenu",[a._locate_event(f),e]);return c}};a.select=
function(b){if(this._select_id!=b)this.editStop(!1),this.unselect(),this._select_id=b,this.updateEvent(b)};a.unselect=function(b){if(!(b&&b!=this._select_id)){var a=this._select_id;this._select_id=null;a&&this.updateEvent(a)}};a.getState=function(){return{mode:this._mode,date:this._date,min_date:this._min_date,max_date:this._max_date,editor_id:this._edit_id,lightbox_id:this._lightbox_id,new_event:this._new_event,select_id:this._select_id,expanded:this.expanded,drag_id:this._drag_id,drag_mode:this._drag_mode}};
a._click={dhx_cal_data:function(b){var e=b?b.target:event.srcElement,d=a._locate_event(e),b=b||event;if(d){if(!a.callEvent("onClick",[d,b])||a.config.readonly)return}else a.callEvent("onEmptyClick",[a.getActionData(b).date,b]);if(d&&a.config.select){a.select(d);var i=e.className;if(i.indexOf("_icon")!=-1)a._click.buttons[i.split(" ")[1].replace("icon_","")](d)}else a._close_not_saved()},dhx_cal_prev_button:function(){a._click.dhx_cal_next_button(0,-1)},dhx_cal_next_button:function(b,e){a.setCurrentView(a.date.add(a.date[a._mode+
"_start"](a._date),e||1,a._mode))},dhx_cal_today_button:function(){a.callEvent("onBeforeTodayDisplayed",[])&&a.setCurrentView(new Date)},dhx_cal_tab:function(){var b=this.getAttribute("name"),e=b.substring(0,b.search("_tab"));a.setCurrentView(a._date,e)},buttons:{"delete":function(b){var e=a.locale.labels.confirm_deleting;a._dhtmlx_confirm(e,a.locale.labels.title_confirm_deleting,function(){a.deleteEvent(b)})},edit:function(b){a.edit(b)},save:function(){a.editStop(!0)},details:function(b){a.showLightbox(b)},
cancel:function(){a.editStop(!1)}}};a._dhtmlx_confirm=function(b,a,d){if(!b)return d();var i={text:b};if(a)i.title=a;if(d)i.callback=function(b){b&&d()};dhtmlx.confirm(i)};a.addEventNow=function(b,a,d){var i={};b&&b.constructor.toString().match(/object/i)!==null&&(i=b,b=null);var f=(this.config.event_duration||this.config.time_step)*6E4;b||(b=i.start_date||Math.round((new Date).valueOf()/f)*f);var c=new Date(b);if(!a){var h=this.config.first_hour;h>c.getHours()&&(c.setHours(h),b=c.valueOf());a=b.valueOf()+
f}var j=new Date(a);c.valueOf()==j.valueOf()&&j.setTime(j.valueOf()+f);i.start_date=i.start_date||c;i.end_date=i.end_date||j;i.text=i.text||this.locale.labels.new_event;i.id=this._drag_id=this.uid();this._drag_mode="new-size";this._loading=!0;this.addEvent(i);this.callEvent("onEventCreated",[this._drag_id,d]);this._loading=!1;this._drag_event={};this._on_mouse_up(d)};a._on_dbl_click=function(b,e){e=e||b.target||b.srcElement;if(!this.config.readonly){var d=e.className.split(" ")[0];switch(d){case "dhx_scale_holder":case "dhx_scale_holder_now":case "dhx_month_body":case "dhx_wa_day_data":case "dhx_marked_timespan":if(!a.config.dblclick_create)break;
this.addEventNow(this.getActionData(b).date,null,b);break;case "dhx_cal_event":case "dhx_wa_ev_body":case "dhx_agenda_line":case "dhx_grid_event":case "dhx_cal_event_line":case "dhx_cal_event_clear":var i=this._locate_event(e);if(!this.callEvent("onDblClick",[i,b]))break;this.config.details_on_dblclick||this._table_view||!this.getEvent(i)._timed||!this.config.select?this.showLightbox(i):this.edit(i);break;case "dhx_time_block":case "dhx_cal_container":break;default:var f=this["dblclick_"+d];if(f)f.call(this,
b);else if(e.parentNode&&e!=this)return a._on_dbl_click(b,e.parentNode)}}};a._mouse_coords=function(b){var e,d=document.body,i=document.documentElement;e=b.pageX||b.pageY?{x:b.pageX,y:b.pageY}:{x:b.clientX+(d.scrollLeft||i.scrollLeft||0)-d.clientLeft,y:b.clientY+(d.scrollTop||i.scrollTop||0)-d.clientTop};e.x-=getAbsoluteLeft(this._obj)+(this._table_view?0:this.xy.scale_width);e.y-=getAbsoluteTop(this._obj)+this.xy.nav_height+(this._dy_shift||0)+this.xy.scale_height-this._els.dhx_cal_data[0].scrollTop;
e.ev=b;var f=this["mouse_"+this._mode];if(f)return f.call(this,e);if(this._table_view){if(!this._cols||!this._colsS)return e;for(var c=0,c=1;c<this._colsS.heights.length;c++)if(this._colsS.heights[c]>e.y)break;e.y=Math.ceil((Math.max(0,e.x/this._cols[0])+Math.max(0,c-1)*7)*1440/this.config.time_step);if(a._drag_mode||this._mode=="month")e.y=(Math.max(0,Math.ceil(e.x/this._cols[0])-1)+Math.max(0,c-1)*7)*1440/this.config.time_step;e.x=0}else e.x=Math.min(this._cols.length-1,Math.max(0,Math.ceil(e.x/
this._cols[0])-1)),e.y=Math.max(0,Math.ceil(e.y*60/(this.config.time_step*this.config.hour_size_px))-1)+this.config.first_hour*(60/this.config.time_step);return e};a._close_not_saved=function(){if((new Date).valueOf()-(a._new_event||0)>500&&a._edit_id){var b=a.locale.labels.confirm_closing;a._dhtmlx_confirm(b,a.locale.labels.title_confirm_closing,function(){a.editStop(a.config.positive_closing)})}};a._correct_shift=function(b,e){return b-=((new Date(a._min_date)).getTimezoneOffset()-(new Date(b)).getTimezoneOffset())*
6E4*(e?-1:1)};a._on_mouse_move=function(b){if(this._drag_mode){var e=this._mouse_coords(b);if(!this._drag_pos||e.force_redraw||this._drag_pos.x!=e.x||this._drag_pos.y!=e.y){var d,i;this._edit_id!=this._drag_id&&this._close_not_saved();this._drag_pos=e;if(this._drag_mode=="create"){this._close_not_saved();this._loading=!0;d=this._get_date_from_pos(e).valueOf();var c=this.callEvent("onBeforeEventCreated",[b]);if(!c)return;if(!this._drag_start){this._drag_start=d;return}i=d;var g=new Date(this._drag_start),
h=new Date(i);if((this._mode=="day"||this._mode=="week")&&g.getHours()==h.getHours()&&g.getMinutes()==h.getMinutes())h=new Date(this._drag_start+1E3);this._drag_id=this.uid();this.addEvent(g,h,this.locale.labels.new_event,this._drag_id,e.fields);this.callEvent("onEventCreated",[this._drag_id,b]);this._loading=!1;this._drag_mode="new-size"}var j=this.getEvent(this._drag_id);if(this._drag_mode=="move")d=this._min_date.valueOf()+(e.y*this.config.time_step+e.x*1440)*6E4,!e.custom&&this._table_view&&(d+=
this.date.time_part(j.start_date)*1E3),d=this._correct_shift(d),i=j.end_date.valueOf()-(j.start_date.valueOf()-d);else{d=j.start_date.valueOf();i=j.end_date.valueOf();if(this._table_view){var n=this._min_date.valueOf()+e.y*this.config.time_step*6E4+(e.custom?0:864E5);this._mode=="month"&&(n=this._correct_shift(n,!1));e.resize_from_start?d=n:i=n}else if(i=this.date.date_part(new Date(j.end_date)).valueOf()+e.y*this.config.time_step*6E4,this._els.dhx_cal_data[0].style.cursor="s-resize",this._mode==
"week"||this._mode=="day")i=this._correct_shift(i);if(this._drag_mode=="new-size")if(i<=this._drag_start){var l=e.shift||(this._table_view&&!e.custom?864E5:0);d=i-(e.shift?0:l);i=this._drag_start+(l||this.config.time_step*6E4)}else d=this._drag_start;else i<=d&&(i=d+this.config.time_step*6E4)}var k=new Date(i-1),m=new Date(d);if(this._table_view||k.getDate()==m.getDate()&&k.getHours()<this.config.last_hour||a._allow_dnd)if(j.start_date=m,j.end_date=new Date(i),this.config.update_render){var r=a._els.dhx_cal_data[0].scrollTop;
this.update_view();a._els.dhx_cal_data[0].scrollTop=r}else this.updateEvent(this._drag_id);this._table_view&&this.for_rendered(this._drag_id,function(b){b.className+=" dhx_in_move"})}}else if(a.checkEvent("onMouseMove")){var p=this._locate_event(b.target||b.srcElement);this.callEvent("onMouseMove",[p,b])}};a._on_mouse_down=function(b,e){if(b.button!=2&&!this.config.readonly&&!this._drag_mode){var e=e||b.target||b.srcElement,d=e.className&&e.className.split(" ")[0];switch(d){case "dhx_cal_event_line":case "dhx_cal_event_clear":if(this._table_view)this._drag_mode=
"move";break;case "dhx_event_move":case "dhx_wa_ev_body":this._drag_mode="move";break;case "dhx_event_resize":this._drag_mode="resize";break;case "dhx_scale_holder":case "dhx_scale_holder_now":case "dhx_month_body":case "dhx_matrix_cell":case "dhx_marked_timespan":this._drag_mode="create";this.unselect(this._select_id);break;case "":if(e.parentNode)return a._on_mouse_down(b,e.parentNode);default:if(a.checkEvent("onMouseDown")&&a.callEvent("onMouseDown",[d])&&e.parentNode&&e!=this)return a._on_mouse_down(b,
e.parentNode);this._drag_id=this._drag_mode=null}if(this._drag_mode){var i=this._locate_event(e);!this.config["drag_"+this._drag_mode]||!this.callEvent("onBeforeDrag",[i,this._drag_mode,b])?this._drag_mode=this._drag_id=0:(this._drag_id=i,this._drag_event=a._lame_clone(this.getEvent(this._drag_id)||{}))}this._drag_start=null}};a._on_mouse_up=function(b){if(this._drag_mode&&this._drag_id){this._els.dhx_cal_data[0].style.cursor="default";var e=this.getEvent(this._drag_id);if(this._drag_event._dhx_changed||
!this._drag_event.start_date||e.start_date.valueOf()!=this._drag_event.start_date.valueOf()||e.end_date.valueOf()!=this._drag_event.end_date.valueOf()){var d=this._drag_mode=="new-size";if(this.callEvent("onBeforeEventChanged",[e,b,d,this._drag_event])){var i=this._drag_id;this._drag_id=this._drag_mode=null;if(d&&this.config.edit_on_create){this.unselect();this._new_event=new Date;if(this._table_view||this.config.details_on_create||!this.config.select)return this.showLightbox(i);this._drag_pos=!0;
this._select_id=this._edit_id=i}else this._new_event||this.callEvent(d?"onEventAdded":"onEventChanged",[i,this.getEvent(i)])}else d?this.deleteEvent(e.id,!0):(this._drag_event._dhx_changed=!1,a._lame_copy(e,this._drag_event),this.updateEvent(e.id))}this._drag_pos&&this.render_view_data()}this._drag_pos=this._drag_mode=this._drag_id=null};a.update_view=function(){this._reset_scale();if(this._load_mode&&this._load())return this._render_wait=!0;this.render_view_data()};a.updateView=function(b,a){var b=
b||this._date,a=a||this._mode,d="dhx_cal_data";this._mode?this._obj.className=this._obj.className.replace("dhx_scheduler_"+this._mode,"dhx_scheduler_"+a):this._obj.className+=" dhx_scheduler_"+a;var i=this._mode==a&&this.config.preserve_scroll?this._els[d][0].scrollTop:!1;if(this[this._mode+"_view"]&&a&&this._mode!=a)this[this._mode+"_view"](!1);this._close_not_saved();var c="dhx_multi_day";this._els[c]&&(this._els[c][0].parentNode.removeChild(this._els[c][0]),this._els[c]=null);this._mode=a;this._date=
b;this._table_view=this._mode=="month";for(var g=this._els.dhx_cal_tab,h=0;h<g.length;h++){var j=g[h].className,j=j.replace(/ active/g,"");g[h].getAttribute("name")==this._mode+"_tab"&&(j+=" active");g[h].className=j}var n=this[this._mode+"_view"];n?n(!0):this.update_view();if(typeof i=="number")this._els[d][0].scrollTop=i};a.setCurrentView=function(b,a){this.callEvent("onBeforeViewChange",[this._mode,this._date,a,b])&&(this.updateView(b,a),this.callEvent("onViewChange",[this._mode,this._date]))};
a._render_x_header=function(b,a,d,i){var c=document.createElement("DIV");c.className="dhx_scale_bar";this.set_xy(c,this._cols[b]-1,this.xy.scale_height-2,a,0);c.innerHTML=this.templates[this._mode+"_scale_date"](d,this._mode);i.appendChild(c)};a._reset_scale=function(){if(this.templates[this._mode+"_date"]){var b=this._els.dhx_cal_header[0],e=this._els.dhx_cal_data[0],d=this.config;b.innerHTML="";e.scrollTop=0;e.innerHTML="";var i=(d.readonly||!d.drag_resize?" dhx_resize_denied":"")+(d.readonly||
!d.drag_move?" dhx_move_denied":"");if(i)e.className="dhx_cal_data"+i;this._scales={};this._cols=[];this._colsS={height:0};this._dy_shift=0;this.set_sizes();var c=parseInt(b.style.width,10),g=0,h,j,n,l;j=this.date[this._mode+"_start"](new Date(this._date.valueOf()));h=n=this._table_view?a.date.week_start(j):j;l=this.date.date_part(new Date);var k=a.date.add(j,1,this._mode),m=7;if(!this._table_view){var r=this.date["get_"+this._mode+"_end"];r&&(k=r(j));m=Math.round((k.valueOf()-j.valueOf())/864E5)}this._min_date=
h;this._els.dhx_cal_date[0].innerHTML=this.templates[this._mode+"_date"](j,k,this._mode);for(var p=0;p<m;p++){this._cols[p]=Math.floor(c/(m-p));this._render_x_header(p,g,h,b);if(!this._table_view){var q=document.createElement("DIV"),s="dhx_scale_holder";h.valueOf()==l.valueOf()&&(s="dhx_scale_holder_now");q.className=s+" "+this.templates.week_date_class(h,l);this.set_xy(q,this._cols[p]-1,d.hour_size_px*(d.last_hour-d.first_hour),g+this.xy.scale_width+1,0);e.appendChild(q);this.callEvent("onScaleAdd",
[q,h])}h=this.date.add(h,1,"day");c-=this._cols[p];g+=this._cols[p];this._colsS[p]=(this._cols[p-1]||0)+(this._colsS[p-1]||(this._table_view?0:this.xy.scale_width+2));this._colsS.col_length=m+1}this._max_date=h;this._colsS[m]=this._cols[m-1]+this._colsS[m-1];if(this._table_view)this._reset_month_scale(e,j,n);else if(this._reset_hours_scale(e,j,n),d.multi_day){var o="dhx_multi_day";this._els[o]&&(this._els[o][0].parentNode.removeChild(this._els[o][0]),this._els[o]=null);var t=this._els.dhx_cal_navline[0],
u=t.offsetHeight+this._els.dhx_cal_header[0].offsetHeight+1,v=document.createElement("DIV");v.className=o;v.style.visibility="hidden";this.set_xy(v,this._colsS[this._colsS.col_length-1]+this.xy.scroll_width,0,0,u);e.parentNode.insertBefore(v,e);var w=v.cloneNode(!0);w.className=o+"_icon";w.style.visibility="hidden";this.set_xy(w,this.xy.scale_width,0,0,u);v.appendChild(w);this._els[o]=[v,w];this._els[o][0].onclick=this._click.dhx_cal_data}}};a._reset_hours_scale=function(b){var e=document.createElement("DIV");
e.className="dhx_scale_holder";for(var d=new Date(1980,1,1,this.config.first_hour,0,0),i=this.config.first_hour*1;i<this.config.last_hour;i++){var c=document.createElement("DIV");c.className="dhx_scale_hour";c.style.height=this.config.hour_size_px-(this._quirks?0:1)+"px";c.style.width=this.xy.scale_width+"px";c.innerHTML=a.templates.hour_scale(d);e.appendChild(c);d=this.date.add(d,1,"hour")}b.appendChild(e);if(this.config.scroll_hour)b.scrollTop=this.config.hour_size_px*(this.config.scroll_hour-this.config.first_hour)};
a._reset_month_scale=function(b,e,d){var i=a.date.add(e,1,"month"),c=new Date;this.date.date_part(c);this.date.date_part(d);var g=Math.ceil(Math.round((i.valueOf()-d.valueOf())/864E5)/7),h=[],j=Math.floor(b.clientHeight/g)-22;this._colsS.height=j+22;for(var n=this._colsS.heights=[],l=0;l<=7;l++)h[l]=" style='height:"+j+"px; width:"+((this._cols[l]||0)-1)+"px;' ";var k=0;this._min_date=d;for(var m="<table cellpadding='0' cellspacing='0'>",r=[],l=0;l<g;l++){m+="<tr>";for(var p=0;p<7;p++){m+="<td";var q=
"";d<e?q="dhx_before":d>=i?q="dhx_after":d.valueOf()==c.valueOf()&&(q="dhx_now");m+=" class='"+q+" "+this.templates.month_date_class(d,c)+"' ";m+="><div class='dhx_month_head'>"+this.templates.month_day(d)+"</div><div class='dhx_month_body' "+h[p]+"></div></td>";r.push(d);d=this.date.add(d,1,"day")}m+="</tr>";n[l]=k;k+=this._colsS.height}m+="</table>";this._max_date=d;b.innerHTML=m;this._scales={};for(var s=b.getElementsByTagName("div"),l=0;l<r.length;l++){var o=s[l*2+1],t=r[l];this._scales[+t]=o}for(l=
0;l<r.length;l++)t=r[l],this.callEvent("onScaleAdd",[this._scales[+t],t]);return d};a.getLabel=function(b,a){for(var d=this.config.lightbox.sections,i=0;i<d.length;i++)if(d[i].map_to==b)for(var c=d[i].options,g=0;g<c.length;g++)if(c[g].key==a)return c[g].label;return""};a.updateCollection=function(b,e){var d=a.serverList(b);if(!d)return!1;d.splice(0,d.length);d.push.apply(d,e||[]);a.callEvent("onOptionsLoad",[]);a.resetLightbox();return!0};a._lame_clone=function(b,e){var d,i,c,e=e||[];for(d=0;d<e.length;d+=
2)if(b===e[d])return e[d+1];if(b&&typeof b=="object"){c={};i=[Array,Date,Number,String,Boolean];for(d=0;d<i.length;d++)b instanceof i[d]&&(c=d?new i[d](b):new i[d]);e.push(b,c);for(d in b)Object.prototype.hasOwnProperty.apply(b,[d])&&(c[d]=a._lame_clone(b[d],e))}return c||b};a._lame_copy=function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b};a._get_date_from_pos=function(b){var a=this._min_date.valueOf()+(b.y*this.config.time_step+(this._table_view?0:b.x)*1440)*6E4;return new Date(this._correct_shift(a))};
a.getActionData=function(b){var a=this._mouse_coords(b);return{date:this._get_date_from_pos(a),section:a.section}};a.date={init:function(){for(var b=a.locale.date.month_short,e=a.locale.date.month_short_hash={},d=0;d<b.length;d++)e[b[d]]=d;b=a.locale.date.month_full;e=a.locale.date.month_full_hash={};for(d=0;d<b.length;d++)e[b[d]]=d},date_part:function(b){b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);b.getHours()!=0&&b.setTime(b.getTime()+36E5*(24-b.getHours()));return b},time_part:function(b){return(b.valueOf()/
1E3-b.getTimezoneOffset()*60)%86400},week_start:function(b){var e=b.getDay();a.config.start_on_monday&&(e===0?e=6:e--);return this.date_part(this.add(b,-1*e,"day"))},month_start:function(b){b.setDate(1);return this.date_part(b)},year_start:function(b){b.setMonth(0);return this.month_start(b)},day_start:function(b){return this.date_part(b)},add:function(b,e,d){var i=new Date(b.valueOf());switch(d){case "week":e*=7;case "day":i.setDate(i.getDate()+e);!b.getHours()&&i.getHours()&&i.setTime(i.getTime()+
36E5*(24-i.getHours()));break;case "month":var c=i.getMonth()+e,g=new Date(i);i.setMonth(c);i.getMonth()!=c&&i.getMonth()!=c%12&&(g.setDate(1),g.setMonth(c),g.setDate((new Date(g.getFullYear(),c+1,0)).getDate()),i=g);break;case "year":i.setYear(i.getFullYear()+e);break;case "hour":i.setHours(i.getHours()+e);break;case "minute":i.setMinutes(i.getMinutes()+e);break;default:return a.date["add_"+d](b,e,d)}return i},to_fixed:function(b){return b<10?"0"+b:b},copy:function(b){return new Date(b.valueOf())},
date_to_str:function(b,a){b=b.replace(/%[a-zA-Z]/g,function(b){switch(b){case "%d":return'"+scheduler.date.to_fixed(date.getDate())+"';case "%m":return'"+scheduler.date.to_fixed((date.getMonth()+1))+"';case "%j":return'"+date.getDate()+"';case "%n":return'"+(date.getMonth()+1)+"';case "%y":return'"+scheduler.date.to_fixed(date.getFullYear()%100)+"';case "%Y":return'"+date.getFullYear()+"';case "%D":return'"+scheduler.locale.date.day_short[date.getDay()]+"';case "%l":return'"+scheduler.locale.date.day_full[date.getDay()]+"';
case "%M":return'"+scheduler.locale.date.month_short[date.getMonth()]+"';case "%F":return'"+scheduler.locale.date.month_full[date.getMonth()]+"';case "%h":return'"+scheduler.date.to_fixed((date.getHours()+11)%12+1)+"';case "%g":return'"+((date.getHours()+11)%12+1)+"';case "%G":return'"+date.getHours()+"';case "%H":return'"+scheduler.date.to_fixed(date.getHours())+"';case "%i":return'"+scheduler.date.to_fixed(date.getMinutes())+"';case "%a":return'"+(date.getHours()>11?"pm":"am")+"';case "%A":return'"+(date.getHours()>11?"PM":"AM")+"';
case "%s":return'"+scheduler.date.to_fixed(date.getSeconds())+"';case "%W":return'"+scheduler.date.to_fixed(scheduler.date.getISOWeek(date))+"';default:return b}});a&&(b=b.replace(/date\.get/g,"date.getUTC"));return new Function("date",'return "'+b+'";')},str_to_date:function(b,a){for(var d="var temp=date.match(/[a-zA-Z]+|[0-9]+/g);",i=b.match(/%[a-zA-Z]/g),c=0;c<i.length;c++)switch(i[c]){case "%j":case "%d":d+="set[2]=temp["+c+"]||1;";break;case "%n":case "%m":d+="set[1]=(temp["+c+"]||1)-1;";break;
case "%y":d+="set[0]=temp["+c+"]*1+(temp["+c+"]>50?1900:2000);";break;case "%g":case "%G":case "%h":case "%H":d+="set[3]=temp["+c+"]||0;";break;case "%i":d+="set[4]=temp["+c+"]||0;";break;case "%Y":d+="set[0]=temp["+c+"]||0;";break;case "%a":case "%A":d+="set[3]=set[3]%12+((temp["+c+"]||'').toLowerCase()=='am'?0:12);";break;case "%s":d+="set[5]=temp["+c+"]||0;";break;case "%M":d+="set[1]=scheduler.locale.date.month_short_hash[temp["+c+"]]||0;";break;case "%F":d+="set[1]=scheduler.locale.date.month_full_hash[temp["+
c+"]]||0;"}var g="set[0],set[1],set[2],set[3],set[4],set[5]";a&&(g=" Date.UTC("+g+")");return new Function("date","var set=[0,0,1,0,0,0]; "+d+" return new Date("+g+");")},getISOWeek:function(b){if(!b)return!1;var a=b.getDay();a===0&&(a=7);var d=new Date(b.valueOf());d.setDate(b.getDate()+(4-a));var c=d.getFullYear(),f=Math.round((d.getTime()-(new Date(c,0,1)).getTime())/864E5),g=1+Math.floor(f/7);return g},getUTCISOWeek:function(b){return this.getISOWeek(b)},convert_to_utc:function(b){return new Date(b.getUTCFullYear(),
b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes(),b.getUTCSeconds())}};a.locale={date:{month_full:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),month_short:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),day_full:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),day_short:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(",")},labels:{dhx_cal_today_button:"Today",day_tab:"Day",week_tab:"Week",month_tab:"Month",
new_event:"New event",icon_save:"Save",icon_cancel:"Cancel",icon_details:"Details",icon_edit:"Edit",icon_delete:"Delete",confirm_closing:"",confirm_deleting:"Event will be deleted permanently, are you sure?",section_description:"Description",section_time:"Time period",full_day:"Full day",confirm_recurring:"Do you want to edit the whole set of repeated events?",section_recurring:"Repeat event",button_recurring:"Disabled",button_recurring_open:"Enabled",button_edit_series:"Edit series",button_edit_occurrence:"Edit occurrence",
agenda_tab:"Agenda",date:"Date",description:"Description",year_tab:"Year",week_agenda_tab:"Agenda",grid_tab:"Grid"}};a.config={default_date:"%j %M %Y",month_date:"%F %Y",load_date:"%Y-%m-%d",week_date:"%l",day_date:"%D, %F %j",hour_date:"%H:%i",month_day:"%d",xml_date:"%m/%d/%Y %H:%i",api_date:"%d-%m-%Y %H:%i",hour_size_px:42,time_step:5,start_on_monday:1,first_hour:0,last_hour:24,readonly:!1,drag_resize:1,drag_move:1,drag_create:1,dblclick_create:1,edit_on_create:1,details_on_create:0,click_form_details:0,
cascade_event_display:!1,cascade_event_count:4,cascade_event_margin:30,multi_day_height_limit:0,drag_lightbox:!0,preserve_scroll:!0,select:!0,server_utc:!1,positive_closing:!1,icons_edit:["icon_save","icon_cancel"],icons_select:["icon_details","icon_edit","icon_delete"],buttons_left:["dhx_save_btn","dhx_cancel_btn"],buttons_right:["dhx_delete_btn"],lightbox:{sections:[{name:"description",height:200,map_to:"text",type:"textarea",focus:!0},{name:"time",height:72,type:"time",map_to:"auto"}]},highlight_displayed_event:!0,
displayed_event_color:"#ffc5ab",displayed_event_text_color:"#7e2727"};a.templates={};a.init_templates=function(){var b=a.locale.labels;b.dhx_save_btn=b.icon_save;b.dhx_cancel_btn=b.icon_cancel;b.dhx_delete_btn=b.icon_delete;var e=a.date.date_to_str,d=a.config,c=function(b,a){for(var e in a)b[e]||(b[e]=a[e])};c(a.templates,{day_date:e(d.default_date),month_date:e(d.month_date),week_date:function(b,e){return a.templates.day_date(b)+" &ndash; "+a.templates.day_date(a.date.add(e,-1,"day"))},day_scale_date:e(d.default_date),
month_scale_date:e(d.week_date),week_scale_date:e(d.day_date),hour_scale:e(d.hour_date),time_picker:e(d.hour_date),event_date:e(d.hour_date),month_day:e(d.month_day),xml_date:a.date.str_to_date(d.xml_date,d.server_utc),load_format:e(d.load_date,d.server_utc),xml_format:e(d.xml_date,d.server_utc),api_date:a.date.str_to_date(d.api_date),event_header:function(b,e){return a.templates.event_date(b)+" - "+a.templates.event_date(e)},event_text:function(b,a,e){return e.text},event_class:function(){return""},
month_date_class:function(){return""},week_date_class:function(){return""},event_bar_date:function(b){return a.templates.event_date(b)+" "},event_bar_text:function(b,a,e){return e.text}});this.callEvent("onTemplatesReady",[])};a.uid=function(){if(!this._seed)this._seed=(new Date).valueOf();return this._seed++};a._events={};a.clearAll=function(){this._events={};this._loaded={};this.clear_view()};a.addEvent=function(b,e,d,c,f){if(!arguments.length)return this.addEventNow();var g=b;if(arguments.length!=
1)g=f||{},g.start_date=b,g.end_date=e,g.text=d,g.id=c;g.id=g.id||a.uid();g.text=g.text||"";if(typeof g.start_date=="string")g.start_date=this.templates.api_date(g.start_date);if(typeof g.end_date=="string")g.end_date=this.templates.api_date(g.end_date);var h=(this.config.event_duration||this.config.time_step)*6E4;g.start_date.valueOf()==g.end_date.valueOf()&&g.end_date.setTime(g.end_date.valueOf()+h);g._timed=this.is_one_day_event(g);var j=!this._events[g.id];this._events[g.id]=g;this.event_updated(g);
this._loading||this.callEvent(j?"onEventAdded":"onEventChanged",[g.id,g]);return g.id};a.deleteEvent=function(b,a){var d=this._events[b];if(a||this.callEvent("onBeforeEventDelete",[b,d])&&this.callEvent("onConfirmedBeforeEventDelete",[b,d]))d&&(delete this._events[b],this.unselect(b),this.event_updated(d)),this.callEvent("onEventDeleted",[b,d])};a.getEvent=function(b){return this._events[b]};a.setEvent=function(b,a){this._events[b]=a};a.for_rendered=function(b,a){for(var d=this._rendered.length-1;d>=
0;d--)this._rendered[d].getAttribute("event_id")==b&&a(this._rendered[d],d)};a.changeEventId=function(b,a){if(b!=a){var d=this._events[b];if(d)d.id=a,this._events[a]=d,delete this._events[b];this.for_rendered(b,function(b){b.setAttribute("event_id",a)});if(this._select_id==b)this._select_id=a;if(this._edit_id==b)this._edit_id=a;this.callEvent("onEventIdChange",[b,a])}};(function(){for(var b="text,Text,start_date,StartDate,end_date,EndDate".split(","),e=function(b){return function(e){return a.getEvent(e)[b]}},
d=function(b){return function(e,d){var c=a.getEvent(e);c[b]=d;c._changed=!0;c._timed=this.is_one_day_event(c);a.event_updated(c,!0)}},c=0;c<b.length;c+=2)a["getEvent"+b[c+1]]=e(b[c]),a["setEvent"+b[c+1]]=d(b[c])})();a.event_updated=function(b){this.is_visible_events(b)?this.render_view_data():this.clear_event(b.id)};a.is_visible_events=function(b){return b.start_date<this._max_date&&this._min_date<b.end_date};a.is_one_day_event=function(b){var a=b.end_date.getDate()-b.start_date.getDate();return a?
(a<0&&(a=Math.ceil((b.end_date.valueOf()-b.start_date.valueOf())/864E5)),a==1&&!b.end_date.getHours()&&!b.end_date.getMinutes()&&(b.start_date.getHours()||b.start_date.getMinutes())):b.start_date.getMonth()==b.end_date.getMonth()&&b.start_date.getFullYear()==b.end_date.getFullYear()};a.get_visible_events=function(b){var a=[],d;for(d in this._events)this.is_visible_events(this._events[d])&&(!b||this._events[d]._timed)&&this.filter_event(d,this._events[d])&&a.push(this._events[d]);return a};a.filter_event=
function(b,a){var d=this["filter_"+this._mode];return d?d(b,a):!0};a.render_view_data=function(b,a){if(!b){if(this._not_render){this._render_wait=!0;return}this._render_wait=!1;this.clear_view();b=this.get_visible_events(!(this._table_view||this.config.multi_day))}if(this.config.multi_day&&!this._table_view){for(var d=[],c=[],f=0;f<b.length;f++)b[f]._timed?d.push(b[f]):c.push(b[f]);this._rendered_location=this._els.dhx_multi_day[0];this._table_view=!0;this.render_data(c,a);this._table_view=!1;this._rendered_location=
this._els.dhx_cal_data[0];this._table_view=!1;this.render_data(d,a)}else this._rendered_location=this._els.dhx_cal_data[0],this.render_data(b,a)};a.render_data=function(b,a){for(var b=this._pre_render_events(b,a),d=0;d<b.length;d++)this._table_view?this.render_event_bar(b[d]):this.render_event(b[d])};a._pre_render_events=function(b,e){var d=this.xy.bar_height,c=this._colsS.heights,f=this._colsS.heights=[0,0,0,0,0,0,0],g=this._els.dhx_cal_data[0],b=this._table_view?this._pre_render_events_table(b,
e):this._pre_render_events_line(b,e);if(this._table_view)if(e)this._colsS.heights=c;else{var h=g.firstChild;if(h.rows){for(var j=0;j<h.rows.length;j++){f[j]++;if(f[j]*d>this._colsS.height-22){for(var n=h.rows[j].cells,l=0;l<n.length;l++)n[l].childNodes[1].style.height=f[j]*d+"px";f[j]=(f[j-1]||0)+n[0].offsetHeight}f[j]=(f[j-1]||0)+h.rows[j].cells[0].offsetHeight}f.unshift(0);if(h.parentNode.offsetHeight<h.parentNode.scrollHeight&&!h._h_fix){for(j=0;j<h.rows.length;j++){var k=h.rows[j].cells[6].childNodes[0],
m=k.offsetWidth-a.xy.scroll_width+"px";k.style.width=m;k.nextSibling.style.width=m}h._h_fix=!0}}else if(!b.length&&this._els.dhx_multi_day[0].style.visibility=="visible"&&(f[0]=-1),b.length||f[0]==-1){var r=h.parentNode.childNodes,p=(f[0]+1)*d+1,q=p,s=p+"px";this.config.multi_day_height_limit&&(q=Math.min(p,this.config.multi_day_height_limit),s=q+"px");g.style.top=this._els.dhx_cal_navline[0].offsetHeight+this._els.dhx_cal_header[0].offsetHeight+q+"px";g.style.height=this._obj.offsetHeight-parseInt(g.style.top,
10)-(this.xy.margin_top||0)+"px";var o=this._els.dhx_multi_day[0];o.style.height=s;o.style.visibility=f[0]==-1?"hidden":"visible";var t=this._els.dhx_multi_day[1];t.style.height=s;t.style.visibility=f[0]==-1?"hidden":"visible";t.className=f[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small";this._dy_shift=(f[0]+1)*d;f[0]=0;if(q!=p)g.style.top=parseInt(g.style.top)+2+"px",o.style.overflowY="auto",o.style.width=parseInt(o.style.width)-2+"px",t.style.position="fixed",t.style.top="",t.style.left=""}}return b};
a._get_event_sday=function(b){return Math.floor((b.start_date.valueOf()-this._min_date.valueOf())/864E5)};a._get_event_mapped_end_date=function(b){var a=b.end_date;if(this.config.separate_short_events){var d=(b.end_date-b.start_date)/6E4;d<this._min_mapped_duration&&(a=this.date.add(a,this._min_mapped_duration-d,"minute"))}return a};a._pre_render_events_line=function(b,a){b.sort(function(b,a){return b.start_date.valueOf()==a.start_date.valueOf()?b.id>a.id?1:-1:b.start_date>a.start_date?1:-1});var d=
[],c=[];this._min_mapped_duration=Math.ceil(this.xy.min_event_height*60/this.config.hour_size_px);for(var f=0;f<b.length;f++){var g=b[f],h=g.start_date,j=g.end_date,n=h.getHours(),l=j.getHours();g._sday=this._get_event_sday(g);d[g._sday]||(d[g._sday]=[]);if(!a){g._inner=!1;for(var k=d[g._sday];k.length;){var m=k[k.length-1],r=this._get_event_mapped_end_date(m);if(r.valueOf()<=g.start_date.valueOf())k.splice(k.length-1,1);else break}for(var p=!1,q=0;q<k.length;q++)if(m=k[q],r=this._get_event_mapped_end_date(m),
r.valueOf()<=g.start_date.valueOf()){p=!0;g._sorder=m._sorder;k.splice(q,1);g._inner=!0;break}if(k.length)k[k.length-1]._inner=!0;if(!p)if(k.length)if(k.length<=k[k.length-1]._sorder){if(k[k.length-1]._sorder)for(q=0;q<k.length;q++){for(var s=!1,o=0;o<k.length;o++)if(k[o]._sorder==q){s=!0;break}if(!s){g._sorder=q;break}}else g._sorder=0;g._inner=!0}else{s=k[0]._sorder;for(q=1;q<k.length;q++)if(k[q]._sorder>s)s=k[q]._sorder;g._sorder=s+1;g._inner=!1}else g._sorder=0;k.push(g);k.length>(k.max_count||
0)?(k.max_count=k.length,g._count=k.length):g._count=g._count?g._count:1}if(n<this.config.first_hour||l>=this.config.last_hour)if(c.push(g),b[f]=g=this._copy_event(g),n<this.config.first_hour&&(g.start_date.setHours(this.config.first_hour),g.start_date.setMinutes(0)),l>=this.config.last_hour&&(g.end_date.setMinutes(0),g.end_date.setHours(this.config.last_hour)),g.start_date>g.end_date||n==this.config.last_hour)b.splice(f,1),f--}if(!a){for(f=0;f<b.length;f++)b[f]._count=d[b[f]._sday].max_count;for(f=
0;f<c.length;f++)c[f]._count=d[c[f]._sday].max_count}return b};a._time_order=function(b){b.sort(function(b,a){return b.start_date.valueOf()==a.start_date.valueOf()?b._timed&&!a._timed?1:!b._timed&&a._timed?-1:b.id>a.id?1:-1:b.start_date>a.start_date?1:-1})};a._pre_render_events_table=function(b,a){this._time_order(b);for(var d=[],c=[[],[],[],[],[],[],[]],f=this._colsS.heights,g,h=this._cols.length,j={},n=0;n<b.length;n++){var l=b[n],k=l.id;j[k]||(j[k]={first_chunk:!0,last_chunk:!0});var m=j[k],r=
g||l.start_date,p=l.end_date;if(r<this._min_date)m.first_chunk=!1,r=this._min_date;if(p>this._max_date)m.last_chunk=!1,p=this._max_date;var q=this.locate_holder_day(r,!1,l);l._sday=q%h;var s=this.locate_holder_day(p,!0,l)||h;l._eday=s%h||h;l._length=s-q;l._sweek=Math.floor((this._correct_shift(r.valueOf(),1)-this._min_date.valueOf())/(864E5*h));var o=c[l._sweek],t;for(t=0;t<o.length;t++)if(o[t]._eday<=l._sday)break;if(!l._sorder||!a)l._sorder=t;if(l._sday+l._length<=h)g=null,d.push(l),o[t]=l,f[l._sweek]=
o.length-1,l._first_chunk=m.first_chunk,l._last_chunk=m.last_chunk;else{var u=this._copy_event(l);u.id=l.id;u._length=h-l._sday;u._eday=h;u._sday=l._sday;u._sweek=l._sweek;u._sorder=l._sorder;u.end_date=this.date.add(r,u._length,"day");if(u._first_chunk=m.first_chunk)m.first_chunk=!1;d.push(u);o[t]=u;g=u.end_date;f[l._sweek]=o.length-1;n--}}return d};a._copy_dummy=function(){var b=new Date(this.start_date),a=new Date(this.end_date);this.start_date=b;this.end_date=a};a._copy_event=function(b){this._copy_dummy.prototype=
b;return new this._copy_dummy};a._rendered=[];a.clear_view=function(){for(var b=0;b<this._rendered.length;b++){var a=this._rendered[b];a.parentNode&&a.parentNode.removeChild(a)}this._rendered=[]};a.updateEvent=function(b){var a=this.getEvent(b);this.clear_event(b);if(a&&this.is_visible_events(a)&&this.filter_event(b,a)&&(this._table_view||this.config.multi_day||a._timed))this.config.update_render?this.render_view_data():this.render_view_data([a],!0)};a.clear_event=function(b){this.for_rendered(b,
function(b,d){b.parentNode&&b.parentNode.removeChild(b);a._rendered.splice(d,1)})};a.render_event=function(b){var e=a.xy.menu_width,d=this.config.use_select_menu_space?0:e;if(!(b._sday<0)){var c=a.locate_holder(b._sday);if(c){var f=b.start_date.getHours()*60+b.start_date.getMinutes(),g=b.end_date.getHours()*60+b.end_date.getMinutes()||a.config.last_hour*60,h=b._count||1,j=b._sorder||0,n=Math.round((f*6E4-this.config.first_hour*36E5)*this.config.hour_size_px/36E5)%(this.config.hour_size_px*24),l=Math.max(a.xy.min_event_height,
(g-f)*this.config.hour_size_px/60),k=Math.floor((c.clientWidth-d)/h),m=j*k+1;b._inner||(k*=h-j);if(this.config.cascade_event_display)var r=this.config.cascade_event_count,p=this.config.cascade_event_margin,m=j%r*p,q=b._inner?(h-j-1)%r*p/2:0,k=Math.floor(c.clientWidth-d-m-q);var s=this._render_v_bar(b.id,d+m,n,k,l,b._text_style,a.templates.event_header(b.start_date,b.end_date,b),a.templates.event_text(b.start_date,b.end_date,b));this._rendered.push(s);c.appendChild(s);m=m+parseInt(c.style.left,10)+
d;if(this._edit_id==b.id){s.style.zIndex=1;k=Math.max(k-4,a.xy.editor_width);s=document.createElement("DIV");s.setAttribute("event_id",b.id);this.set_xy(s,k,l-20,m,n+14);s.className="dhx_cal_editor";var o=document.createElement("DIV");this.set_xy(o,k-6,l-26);o.style.cssText+=";margin:2px 2px 2px 2px;overflow:hidden;";s.appendChild(o);this._els.dhx_cal_data[0].appendChild(s);this._rendered.push(s);o.innerHTML="<textarea class='dhx_cal_editor'>"+b.text+"</textarea>";if(this._quirks7)o.firstChild.style.height=
l-12+"px";this._editor=o.firstChild;this._editor.onkeydown=function(b){if((b||event).shiftKey)return!0;var e=(b||event).keyCode;e==a.keys.edit_save&&a.editStop(!0);e==a.keys.edit_cancel&&a.editStop(!1)};this._editor.onselectstart=function(b){return(b||event).cancelBubble=!0};o.firstChild.focus();this._els.dhx_cal_data[0].scrollLeft=0;o.firstChild.select()}if(this.xy.menu_width!==0&&this._select_id==b.id){if(this.config.cascade_event_display&&this._drag_mode)s.style.zIndex=1;for(var t=this.config["icons_"+
(this._edit_id==b.id?"edit":"select")],u="",v=b.color?"background-color: "+b.color+";":"",w=b.textColor?"color: "+b.textColor+";":"",x=0;x<t.length;x++)u+="<div class='dhx_menu_icon "+t[x]+"' style='"+v+""+w+"' title='"+this.locale.labels[t[x]]+"'></div>";var z=this._render_v_bar(b.id,m-e+1,n,e,t.length*20+26-2,"","<div style='"+v+""+w+"' class='dhx_menu_head'></div>",u,!0);z.style.left=m-e+1;this._els.dhx_cal_data[0].appendChild(z);this._rendered.push(z)}}}};a._render_v_bar=function(b,e,d,c,f,g,
h,j,n){var l=document.createElement("DIV"),k=this.getEvent(b),m=n?"dhx_cal_event dhx_cal_select_menu":"dhx_cal_event",r=a.templates.event_class(k.start_date,k.end_date,k);r&&(m=m+" "+r);var p=k.color?"background:"+k.color+";":"",q=k.textColor?"color:"+k.textColor+";":"",s='<div event_id="'+b+'" class="'+m+'" style="position:absolute; top:'+d+"px; left:"+e+"px; width:"+(c-4)+"px; height:"+f+"px;"+(g||"")+'"></div>';l.innerHTML=s;var o=l.cloneNode(!0).firstChild;if(!a.renderEvent||n||!a.renderEvent(o,
k)){var o=l.firstChild,t='<div class="dhx_event_move dhx_header" style=" width:'+(c-6)+"px;"+p+'" >&nbsp;</div>';t+='<div class="dhx_event_move dhx_title" style="'+p+""+q+'">'+h+"</div>";t+='<div class="dhx_body" style=" width:'+(c-(this._quirks?4:14))+"px; height:"+(f-(this._quirks?20:30)+1)+"px;"+p+""+q+'">'+j+"</div>";var u="dhx_event_resize dhx_footer";n&&(u="dhx_resize_denied "+u);t+='<div class="'+u+'" style=" width:'+(c-8)+"px;"+(n?" margin-top:-1px;":"")+""+p+""+q+'" ></div>';o.innerHTML=
t}return o};a.locate_holder=function(b){return this._mode=="day"?this._els.dhx_cal_data[0].firstChild:this._els.dhx_cal_data[0].childNodes[b]};a.locate_holder_day=function(b,a){var d=Math.floor((this._correct_shift(b,1)-this._min_date)/864E5);a&&this.date.time_part(b)&&d++;return d};a.render_event_bar=function(b){var e=this._rendered_location,d=this._colsS[b._sday],c=this._colsS[b._eday];c==d&&(c=this._colsS[b._eday+1]);var f=this.xy.bar_height,g=this._colsS.heights[b._sweek]+(this._colsS.height?
this.xy.month_scale_height+2:2)+b._sorder*f,h=document.createElement("DIV"),j="dhx_cal_event_clear";b._timed||(j="dhx_cal_event_line",b.hasOwnProperty("_first_chunk")&&b._first_chunk&&(j+=" dhx_cal_event_line_start"),b.hasOwnProperty("_last_chunk")&&b._last_chunk&&(j+=" dhx_cal_event_line_end"));var n=a.templates.event_class(b.start_date,b.end_date,b);n&&(j=j+" "+n);var l=b.color?"background:"+b.color+";":"",k=b.textColor?"color:"+b.textColor+";":"",m='<div event_id="'+b.id+'" class="'+j+'" style="position:absolute; top:'+
g+"px; left:"+d+"px; width:"+(c-d-15)+"px;"+k+""+l+""+(b._text_style||"")+'">',b=a.getEvent(b.id);b._timed&&(m+=a.templates.event_bar_date(b.start_date,b.end_date,b));m+=a.templates.event_bar_text(b.start_date,b.end_date,b)+"</div>";m+="</div>";h.innerHTML=m;this._rendered.push(h.firstChild);e.appendChild(h.firstChild)};a._locate_event=function(b){for(var a=null;b&&!a&&b.getAttribute;)a=b.getAttribute("event_id"),b=b.parentNode;return a};a.edit=function(b){if(this._edit_id!=b)this.editStop(!1,b),
this._edit_id=b,this.updateEvent(b)};a.editStop=function(b,a){if(!(a&&this._edit_id==a)){var d=this.getEvent(this._edit_id);if(d){if(b)d.text=this._editor.value;this._editor=this._edit_id=null;this.updateEvent(d.id);this._edit_stop_event(d,b)}}};a._edit_stop_event=function(b,a){this._new_event?(a?this.callEvent("onEventAdded",[b.id,b]):b&&this.deleteEvent(b.id,!0),this._new_event=null):a&&this.callEvent("onEventChanged",[b.id,b])};a.getEvents=function(b,a){var d=[],c;for(c in this._events){var f=
this._events[c];f&&(!b&&!a||f.start_date<a&&f.end_date>b)&&d.push(f)}return d};a.getRenderedEvent=function(b){if(b){for(var e=a._rendered,d=0;d<e.length;d++){var c=e[d];if(c.getAttribute("event_id")==b)return c}return null}};a.showEvent=function(b,e){var d=typeof b=="number"||typeof b=="string"?a.getEvent(b):b,e=e||a._mode;if(d&&(!this.checkEvent("onBeforeEventDisplay")||this.callEvent("onBeforeEventDisplay",[d,e]))){var c=a.config.scroll_hour;a.config.scroll_hour=d.start_date.getHours();var f=a.config.preserve_scroll;
a.config.preserve_scroll=!1;var g=d.color,h=d.textColor;if(a.config.highlight_displayed_event)d.color=a.config.displayed_event_color,d.textColor=a.config.displayed_event_text_color;a.setCurrentView(new Date(d.start_date),e);d.color=g;d.textColor=h;a.config.scroll_hour=c;a.config.preserve_scroll=f;if(a.matrix&&a.matrix[e])a._els.dhx_cal_data[0].scrollTop=getAbsoluteTop(a.getRenderedEvent(d.id));a.callEvent("onAfterEventDisplay",[d,e])}};a._loaded={};a._load=function(b,e){b=b||this._load_url;b+=(b.indexOf("?")==
-1?"?":"&")+"timeshift="+(new Date).getTimezoneOffset();this.config.prevent_cache&&(b+="&uid="+this.uid());var d,e=e||this._date;if(this._load_mode){for(var c=this.templates.load_format,e=this.date[this._load_mode+"_start"](new Date(e.valueOf()));e>this._min_date;)e=this.date.add(e,-1,this._load_mode);d=e;for(var f=!0;d<this._max_date;)d=this.date.add(d,1,this._load_mode),this._loaded[c(e)]&&f?e=this.date.add(e,1,this._load_mode):f=!1;var g=d;do d=g,g=this.date.add(d,-1,this._load_mode);while(g>e&&
this._loaded[c(g)]);if(d<=e)return!1;for(dhtmlxAjax.get(b+"&from="+c(e)+"&to="+c(d),function(b){a.on_load(b)});e<d;)this._loaded[c(e)]=!0,e=this.date.add(e,1,this._load_mode)}else dhtmlxAjax.get(b,function(b){a.on_load(b)});this.callEvent("onXLS",[]);return!0};a.on_load=function(b){var e;e=this._process?this[this._process].parse(b.xmlDoc.responseText):this._magic_parser(b);a._process_loading(e);this.callEvent("onXLE",[])};a._process_loading=function(b){this._not_render=this._loading=!0;for(var a=
0;a<b.length;a++)this.callEvent("onEventLoading",[b[a]])&&this.addEvent(b[a]);this._not_render=!1;this._render_wait&&this.render_view_data();this._loading=!1;this._after_call&&this._after_call();this._after_call=null};a._init_event=function(b){b.text=b.text||b._tagvalue||"";b.start_date=b.start_date?a.templates.xml_date(b.start_date):null;b.end_date=b.end_date?a.templates.xml_date(b.end_date):null};a.json={};a.json.parse=function(b){if(typeof b=="string")a._temp=eval("("+b+")"),b=a._temp?a._temp.data||
a._temp:[];if(b.dhx_security)dhtmlx.security_key=b.dhx_security;var e=a._temp&&a._temp.collections?a._temp.collections:{},d=!1,c;for(c in e)if(e.hasOwnProperty(c)){var d=!0,f=e[c],g=a.serverList[c];if(g){g.splice(0,g.length);for(var h=0;h<f.length;h++){var j=f[h],n={key:j.value,label:j.label},l;for(l in j)if(j.hasOwnProperty(l)&&!(l=="value"||l=="label"))n[l]=j[l];g.push(n)}}}d&&a.callEvent("onOptionsLoad",[]);for(var k=[],m=0;m<b.length;m++){var r=b[m];a._init_event(r);k.push(r)}return k};a.parse=
function(b,a){this._process=a;this.on_load({xmlDoc:{responseText:b}})};a.load=function(b,a,d){if(typeof a=="string")this._process=a,a=d;this._load_url=b;this._after_call=a;this._load(b,this._date)};a.setLoadMode=function(b){b=="all"&&(b="");this._load_mode=b};a.refresh=function(){alert("not implemented")};a.serverList=function(b,a){return a?this.serverList[b]=a.slice(0):this.serverList[b]=this.serverList[b]||[]};a._userdata={};a._magic_parser=function(b){var e;if(!b.getXMLTopNode){var d=b.xmlDoc.responseText,
b=new dtmlXMLLoaderObject(function(){});b.loadXMLString(d)}e=b.getXMLTopNode("data");if(e.tagName!="data")return[];var c=e.getAttribute("dhx_security");if(c)dhtmlx.security_key=c;for(var f=b.doXPath("//coll_options"),g=0;g<f.length;g++){var h=f[g].getAttribute("for"),j=this.serverList[h];if(j){j.splice(0,j.length);for(var n=b.doXPath(".//item",f[g]),l=0;l<n.length;l++){for(var k=n[l],m=k.attributes,r={key:n[l].getAttribute("value"),label:n[l].getAttribute("label")},p=0;p<m.length;p++){var q=m[p];
if(!(q.nodeName=="value"||q.nodeName=="label"))r[q.nodeName]=q.nodeValue}j.push(r)}}}f.length&&a.callEvent("onOptionsLoad",[]);for(var s=b.doXPath("//userdata"),g=0;g<s.length;g++){var o=this.xmlNodeToJSON(s[g]);this._userdata[o.name]=o.text}var t=[];e=b.doXPath("//event");for(g=0;g<e.length;g++){var u=t[g]=this.xmlNodeToJSON(e[g]);a._init_event(u)}return t};a.xmlNodeToJSON=function(b){for(var a={},d=0;d<b.attributes.length;d++)a[b.attributes[d].name]=b.attributes[d].value;for(d=0;d<b.childNodes.length;d++){var c=
b.childNodes[d];c.nodeType==1&&(a[c.tagName]=c.firstChild?c.firstChild.nodeValue:"")}if(!a.text)a.text=b.firstChild?b.firstChild.nodeValue:"";return a};a.attachEvent("onXLS",function(){if(this.config.show_loading===!0){var b;b=this.config.show_loading=document.createElement("DIV");b.className="dhx_loading";b.style.left=Math.round((this._x-128)/2)+"px";b.style.top=Math.round((this._y-15)/2)+"px";this._obj.appendChild(b)}});a.attachEvent("onXLE",function(){var b;if((b=this.config.show_loading)&&typeof b==
"object")this._obj.removeChild(b),this.config.show_loading=!0});a.ical={parse:function(b){var a=b.match(RegExp(this.c_start+"[^\u000c]*"+this.c_end,""));if(a.length){a[0]=a[0].replace(/[\r\n]+(?=[a-z \t])/g," ");a[0]=a[0].replace(/\;[^:\r\n]*/g,"");for(var d=[],c,f=RegExp("(?:"+this.e_start+")([^\u000c]*?)(?:"+this.e_end+")","g");c=f.exec(a);){for(var g={},h,j=/[^\r\n]+[\r\n]+/g;h=j.exec(c[1]);)this.parse_param(h.toString(),g);if(g.uid&&!g.id)g.id=g.uid;d.push(g)}return d}},parse_param:function(b,
a){var d=b.indexOf(":");if(d!=-1){var c=b.substr(0,d).toLowerCase(),f=b.substr(d+1).replace(/\\\,/g,",").replace(/[\r\n]+$/,"");c=="summary"?c="text":c=="dtstart"?(c="start_date",f=this.parse_date(f,0,0)):c=="dtend"&&(c="end_date",f=this.parse_date(f,0,0));a[c]=f}},parse_date:function(b,e,d){var c=b.split("T");c[1]&&(e=c[1].substr(0,2),d=c[1].substr(2,2));var f=c[0].substr(0,4),g=parseInt(c[0].substr(4,2),10)-1,h=c[0].substr(6,2);return a.config.server_utc&&!c[1]?new Date(Date.UTC(f,g,h,e,d)):new Date(f,
g,h,e,d)},c_start:"BEGIN:VCALENDAR",e_start:"BEGIN:VEVENT",e_end:"END:VEVENT",c_end:"END:VCALENDAR"};a.lightbox={};a.formSection=function(b){for(var e=this.config.lightbox.sections,d=0;d<e.length;d++)if(e[d].name==b)break;var c=e[d];a._lightbox||a.getLightbox();var f=document.getElementById(c.id),g=f.nextSibling,h={section:c,header:f,node:g,getValue:function(b){return a.form_blocks[c.type].get_value(g,b||{},c)},setValue:function(b,e){return a.form_blocks[c.type].set_value(g,b,e||{},c)}},j=a.lightbox["get_"+
c.type+"_control"];return j?j(h):h};a.lightbox.get_template_control=function(b){b.control=b.node;return b};a.lightbox.get_select_control=function(b){b.control=b.node.getElementsByTagName("select")[0];return b};a.lightbox.get_textarea_control=function(b){b.control=b.node.getElementsByTagName("textarea")[0];return b};a.lightbox.get_time_control=function(b){b.control=b.node.getElementsByTagName("select");return b};a.form_blocks={template:{render:function(b){var a=(b.height||"30")+"px";return"<div class='dhx_cal_ltext dhx_cal_template' style='height:"+
a+";'></div>"},set_value:function(b,a){b.innerHTML=a||""},get_value:function(b){return b.innerHTML||""},focus:function(){}},textarea:{render:function(b){var a=(b.height||"130")+"px";return"<div class='dhx_cal_ltext' style='height:"+a+";'><textarea></textarea></div>"},set_value:function(b,a){b.firstChild.value=a||""},get_value:function(b){return b.firstChild.value},focus:function(b){var a=b.firstChild;a.select();a.focus()}},select:{render:function(b){for(var a=(b.height||"23")+"px",d="<div class='dhx_cal_ltext' style='height:"+
a+";'><select style='width:100%;'>",c=0;c<b.options.length;c++)d+="<option value='"+b.options[c].key+"'>"+b.options[c].label+"</option>";d+="</select></div>";return d},set_value:function(b,a,d,c){var f=b.firstChild;if(!f._dhx_onchange&&c.onchange)f.onchange=c.onchange,f._dhx_onchange=!0;if(typeof a=="undefined")a=(f.options[0]||{}).value;f.value=a||""},get_value:function(b){return b.firstChild.value},focus:function(b){var a=b.firstChild;a.select&&a.select();a.focus()}},time:{render:function(b){if(!b.time_format)b.time_format=
["%H:%i","%d","%m","%Y"];b._time_format_order={};var e=b.time_format,d=a.config,c=this.date.date_part(new Date),f=1440,g=0;a.config.limit_time_select&&(f=60*d.last_hour+1,g=60*d.first_hour,c.setHours(d.first_hour));for(var h="",j=0;j<e.length;j++){var n=e[j];j>0&&(h+=" ");switch(n){case "%Y":b._time_format_order[3]=j;h+="<select>";for(var l=c.getFullYear()-5,k=0;k<10;k++)h+="<option value='"+(l+k)+"'>"+(l+k)+"</option>";h+="</select> ";break;case "%m":b._time_format_order[2]=j;h+="<select>";for(k=
0;k<12;k++)h+="<option value='"+k+"'>"+this.locale.date.month_full[k]+"</option>";h+="</select>";break;case "%d":b._time_format_order[1]=j;h+="<select>";for(k=1;k<32;k++)h+="<option value='"+k+"'>"+k+"</option>";h+="</select>";break;case "%H:%i":b._time_format_order[0]=j;h+="<select>";var k=g,m=c.getDate();for(b._time_values=[];k<f;){var r=this.templates.time_picker(c);h+="<option value='"+k+"'>"+r+"</option>";b._time_values.push(k);c.setTime(c.valueOf()+this.config.time_step*6E4);var p=c.getDate()!=
m?1:0,k=p*1440+c.getHours()*60+c.getMinutes()}h+="</select>"}}return"<div style='height:30px;padding-top:0px;font-size:inherit;' class='dhx_section_time'>"+h+"<span style='font-weight:normal; font-size:10pt;'> &nbsp;&ndash;&nbsp; </span>"+h+"</div>"},set_value:function(b,e,d,c){function f(b,a,e){for(var d=c._time_values,f=e.getHours()*60+e.getMinutes(),g=f,h=!1,l=0;l<d.length;l++){var k=d[l];if(k===f){h=!0;break}k<f&&(g=k)}b[a+j[0]].value=h?f:g;b[a+j[1]].value=e.getDate();b[a+j[2]].value=e.getMonth();
b[a+j[3]].value=e.getFullYear()}var g=a.config,h=b.getElementsByTagName("select"),j=c._time_format_order;if(g.full_day){if(!b._full_day){var n="<label class='dhx_fullday'><input type='checkbox' name='full_day' value='true'> "+a.locale.labels.full_day+"&nbsp;</label></input>";a.config.wide_form||(n=b.previousSibling.innerHTML+n);b.previousSibling.innerHTML=n;b._full_day=!0}var l=b.previousSibling.getElementsByTagName("input")[0];l.checked=a.date.time_part(d.start_date)===0&&a.date.time_part(d.end_date)===
0;h[j[0]].disabled=l.checked;h[j[0]+h.length/2].disabled=l.checked;l.onclick=function(){if(l.checked){var e={};a.form_blocks.time.get_value(b,e,c);var g=a.date.date_part(e.start_date),k=a.date.date_part(e.end_date);if(+k==+g||+k>=+g&&(d.end_date.getHours()!=0||d.end_date.getMinutes()!=0))k=a.date.add(k,1,"day")}h[j[0]].disabled=l.checked;h[j[0]+h.length/2].disabled=l.checked;f(h,0,g||d.start_date);f(h,4,k||d.end_date)}}if(g.auto_end_date&&g.event_duration)for(var k=function(){var b=new Date(h[j[3]].value,
h[j[2]].value,h[j[1]].value,0,h[j[0]].value),e=new Date(b.getTime()+a.config.event_duration*6E4);f(h,4,e)},m=0;m<4;m++)h[m].onchange=k;f(h,0,d.start_date);f(h,4,d.end_date)},get_value:function(b,e,d){s=b.getElementsByTagName("select");var c=d._time_format_order;e.start_date=new Date(s[c[3]].value,s[c[2]].value,s[c[1]].value,0,s[c[0]].value);e.end_date=new Date(s[c[3]+4].value,s[c[2]+4].value,s[c[1]+4].value,0,s[c[0]+4].value);if(e.end_date<=e.start_date)e.end_date=a.date.add(e.start_date,a.config.time_step,
"minute");return{start_date:new Date(e.start_date),end_date:new Date(e.end_date)}},focus:function(b){b.getElementsByTagName("select")[0].focus()}}};a.showCover=function(b){if(b){b.style.display="block";var a=window.pageYOffset||document.body.scrollTop||document.documentElement.scrollTop,d=window.pageXOffset||document.body.scrollLeft||document.documentElement.scrollLeft,c=window.innerHeight||document.documentElement.clientHeight;b.style.top=a?Math.round(a+Math.max((c-b.offsetHeight)/2,0))+"px":Math.round(Math.max((c-
b.offsetHeight)/2,0)+9)+"px";b.style.left=document.documentElement.scrollWidth>document.body.offsetWidth?Math.round(d+(document.body.offsetWidth-b.offsetWidth)/2)+"px":Math.round((document.body.offsetWidth-b.offsetWidth)/2)+"px"}this.show_cover()};a.showLightbox=function(b){if(b)if(this.callEvent("onBeforeLightbox",[b])){var a=this.getLightbox();this.showCover(a);this._fill_lightbox(b,a);this.callEvent("onLightbox",[b])}else if(this._new_event)this._new_event=null};a._fill_lightbox=function(b,e){var d=
this.getEvent(b),c=e.getElementsByTagName("span");a.templates.lightbox_header?(c[1].innerHTML="",c[2].innerHTML=a.templates.lightbox_header(d.start_date,d.end_date,d)):(c[1].innerHTML=this.templates.event_header(d.start_date,d.end_date,d),c[2].innerHTML=(this.templates.event_bar_text(d.start_date,d.end_date,d)||"").substr(0,70));for(var f=this.config.lightbox.sections,g=0;g<f.length;g++){var h=f[g],j=document.getElementById(h.id).nextSibling,n=this.form_blocks[h.type],l=d[h.map_to]!==void 0?d[h.map_to]:
h.default_value;n.set_value.call(this,j,l,d,h);f[g].focus&&n.focus.call(this,j)}a._lightbox_id=b};a._lightbox_out=function(b){for(var a=this.config.lightbox.sections,d=0;d<a.length;d++){var c=document.getElementById(a[d].id),c=c?c.nextSibling:c,f=this.form_blocks[a[d].type],g=f.get_value.call(this,c,b,a[d]);a[d].map_to!="auto"&&(b[a[d].map_to]=g)}return b};a._empty_lightbox=function(b){var e=a._lightbox_id,d=this.getEvent(e),c=this.getLightbox();this._lame_copy(d,b);d._timed=this.is_one_day_event(d);
this.setEvent(d.id,d);this._edit_stop_event(d,!0);this.render_view_data()};a.hide_lightbox=function(){this.hideCover(this.getLightbox());this._lightbox_id=null;this.callEvent("onAfterLightbox",[])};a.hideCover=function(b){if(b)b.style.display="none";this.hide_cover()};a.hide_cover=function(){this._cover&&this._cover.parentNode.removeChild(this._cover);this._cover=null};a.show_cover=function(){this._cover=document.createElement("DIV");this._cover.className="dhx_cal_cover";var b=document.height!==void 0?
document.height:document.body.offsetHeight,a=document.documentElement?document.documentElement.scrollHeight:0;this._cover.style.height=Math.max(b,a)+"px";document.body.appendChild(this._cover)};a.save_lightbox=function(){var b=this._lightbox_out({},this._lame_copy(this.getEvent(this._lightbox_id)));if(!this.checkEvent("onEventSave")||this.callEvent("onEventSave",[this._lightbox_id,b,this._new_event]))this._empty_lightbox(b),this.hide_lightbox()};a.startLightbox=function(b,a){this._lightbox_id=b;this._custom_lightbox=
!0;this._lightbox=a;this.showCover(a)};a.endLightbox=function(b,e){this._edit_stop_event(a.getEvent(this._lightbox_id),b);b&&a.render_view_data();this.hideCover(e);this._lightbox_id=null};a.resetLightbox=function(){a._lightbox&&!a._custom_lightbox&&a._lightbox.parentNode.removeChild(a._lightbox);a._lightbox=null};a.cancel_lightbox=function(){this.callEvent("onEventCancel",[this._lightbox_id,this._new_event]);this.endLightbox(!1);this.hide_lightbox()};a._init_lightbox_events=function(){this.getLightbox().onclick=
function(b){var e=b?b.target:event.srcElement;if(!e.className)e=e.previousSibling;if(e&&e.className)switch(e.className){case "dhx_save_btn":a.save_lightbox();break;case "dhx_delete_btn":var d=a.locale.labels.confirm_deleting;a._dhtmlx_confirm(d,a.locale.labels.title_confirm_deleting,function(){a.deleteEvent(a._lightbox_id);a._new_event=null;a.hide_lightbox()});break;case "dhx_cancel_btn":a.cancel_lightbox();break;default:if(e.getAttribute("dhx_button"))a.callEvent("onLightboxButton",[e.className,
e,b]);else{var c,f,g;if(e.className.indexOf("dhx_custom_button")!=-1)e.className.indexOf("dhx_custom_button_")!=-1?(c=e.parentNode.getAttribute("index"),g=e.parentNode.parentNode):(c=e.getAttribute("index"),g=e.parentNode,e=e.firstChild);c&&(f=a.form_blocks[a.config.lightbox.sections[c].type],f.button_click(c,e,g,g.nextSibling))}}};this.getLightbox().onkeydown=function(b){switch((b||event).keyCode){case a.keys.edit_save:if((b||event).shiftKey)break;a.save_lightbox();break;case a.keys.edit_cancel:a.cancel_lightbox()}}};
a.setLightboxSize=function(){var b=this._lightbox;if(b){var e=b.childNodes[1];e.style.height="0px";e.style.height=e.scrollHeight+"px";b.style.height=e.scrollHeight+a.xy.lightbox_additional_height+"px";e.style.height=e.scrollHeight+"px"}};a._init_dnd_events=function(){dhtmlxEvent(document.body,"mousemove",a._move_while_dnd);dhtmlxEvent(document.body,"mouseup",a._finish_dnd);a._init_dnd_events=function(){}};a._move_while_dnd=function(b){if(a._dnd_start_lb){if(!document.dhx_unselectable)document.body.className+=
" dhx_unselectable",document.dhx_unselectable=!0;var e=a.getLightbox(),d=b&&b.target?[b.pageX,b.pageY]:[event.clientX,event.clientY];e.style.top=a._lb_start[1]+d[1]-a._dnd_start_lb[1]+"px";e.style.left=a._lb_start[0]+d[0]-a._dnd_start_lb[0]+"px"}};a._ready_to_dnd=function(b){var e=a.getLightbox();a._lb_start=[parseInt(e.style.left,10),parseInt(e.style.top,10)];a._dnd_start_lb=b&&b.target?[b.pageX,b.pageY]:[event.clientX,event.clientY]};a._finish_dnd=function(){if(a._lb_start)a._lb_start=a._dnd_start_lb=
!1,document.body.className=document.body.className.replace(" dhx_unselectable",""),document.dhx_unselectable=!1};a.getLightbox=function(){if(!this._lightbox){var b=document.createElement("DIV");b.className="dhx_cal_light";a.config.wide_form&&(b.className+=" dhx_cal_light_wide");a.form_blocks.recurring&&(b.className+=" dhx_cal_light_rec");/msie|MSIE 6/.test(navigator.userAgent)&&(b.className+=" dhx_ie6");b.style.visibility="hidden";for(var e=this._lightbox_template,d=this.config.buttons_left,c=0;c<
d.length;c++)e+="<div class='dhx_btn_set dhx_left_btn_set "+d[c]+"_set'><div dhx_button='1' class='"+d[c]+"'></div><div>"+a.locale.labels[d[c]]+"</div></div>";d=this.config.buttons_right;for(c=0;c<d.length;c++)e+="<div class='dhx_btn_set dhx_right_btn_set "+d[c]+"_set' style='float:right;'><div dhx_button='1' class='"+d[c]+"'></div><div>"+a.locale.labels[d[c]]+"</div></div>";e+="</div>";b.innerHTML=e;if(a.config.drag_lightbox)b.firstChild.onmousedown=a._ready_to_dnd,b.firstChild.onselectstart=function(){return!1},
b.firstChild.style.cursor="pointer",a._init_dnd_events();document.body.insertBefore(b,document.body.firstChild);this._lightbox=b;for(var f=this.config.lightbox.sections,e="",c=0;c<f.length;c++){var g=this.form_blocks[f[c].type];if(g){f[c].id="area_"+this.uid();var h="";f[c].button&&(h="<div class='dhx_custom_button' index='"+c+"'><div class='dhx_custom_button_"+f[c].button+"'></div><div>"+this.locale.labels["button_"+f[c].button]+"</div></div>");this.config.wide_form&&(e+="<div class='dhx_wrap_section'>");
e+="<div id='"+f[c].id+"' class='dhx_cal_lsection'>"+h+this.locale.labels["section_"+f[c].name]+"</div>"+g.render.call(this,f[c]);e+="</div>"}}for(var j=b.getElementsByTagName("div"),c=0;c<j.length;c++){var n=j[c];if(n.className=="dhx_cal_larea"){n.innerHTML=e;break}}this.setLightboxSize();this._init_lightbox_events(this);b.style.display="none";b.style.visibility="visible"}return this._lightbox};a._lightbox_template="<div class='dhx_cal_ltitle'><span class='dhx_mark'>&nbsp;</span><span class='dhx_time'></span><span class='dhx_title'></span></div><div class='dhx_cal_larea'></div>";
a._dp_init=function(b){b._methods=["setEventTextStyle","","changeEventId","deleteEvent"];this.attachEvent("onEventAdded",function(a){!this._loading&&this.validId(a)&&b.setUpdated(a,!0,"inserted")});this.attachEvent("onConfirmedBeforeEventDelete",function(a){if(this.validId(a)){var c=b.getState(a);if(c=="inserted"||this._new_event)return b.setUpdated(a,!1),!0;if(c=="deleted")return!1;if(c=="true_deleted")return!0;b.setUpdated(a,!0,"deleted");return!1}});this.attachEvent("onEventChanged",function(a){!this._loading&&
this.validId(a)&&b.setUpdated(a,!0,"updated")});b._getRowData=function(a){var b=this.obj.getEvent(a),c={},f;for(f in b)f.indexOf("_")!=0&&(c[f]=b[f]&&b[f].getUTCFullYear?this.obj.templates.xml_format(b[f]):b[f]);return c};b._clearUpdateFlag=function(){};b.attachEvent("insertCallback",a._update_callback);b.attachEvent("updateCallback",a._update_callback);b.attachEvent("deleteCallback",function(b,a){this.obj.setUserData(a,this.action_param,"true_deleted");this.obj.deleteEvent(a)})};a.setUserData=function(b,
a,c){b?this.getEvent(b)[a]=c:this._userdata[a]=c};a.getUserData=function(a,c){return a?this.getEvent(a)[c]:this._userdata[c]};a.setEventTextStyle=function(a,c){this.for_rendered(a,function(a){a.style.cssText+=";"+c});var d=this.getEvent(a);d._text_style=c;this.event_updated(d)};a.validId=function(){return!0};a._update_callback=function(b){var c=a.xmlNodeToJSON(b.firstChild);c.text=c.text||c._tagvalue;c.start_date=a.templates.xml_date(c.start_date);c.end_date=a.templates.xml_date(c.end_date);a.addEvent(c)};
for(var c=0;c<Scheduler._schedulerPlugins.length;c++)Scheduler._schedulerPlugins[c](a);a._internal_id=Scheduler._seed++;Scheduler.$syncFactory&&Scheduler.$syncFactory(a);return a};window.scheduler=Scheduler.getSchedulerInstance();
if(dhtmlx&&dhtmlx.attaches)dhtmlx.attaches.attachScheduler=function(a,c,b,e){var b=b||'<div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div><div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div><div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>',d=document.createElement("DIV");d.id="dhxSchedObj_"+this._genStr(12);d.innerHTML='<div id="'+d.id+'" class="dhx_cal_container" style="width:100%; height:100%;"><div class="dhx_cal_navline"><div class="dhx_cal_prev_button">&nbsp;</div><div class="dhx_cal_next_button">&nbsp;</div><div class="dhx_cal_today_button"></div><div class="dhx_cal_date"></div>'+
b+'</div><div class="dhx_cal_header"></div><div class="dhx_cal_data"></div></div>';document.body.appendChild(d.firstChild);this.attachObject(d.id,!1,!0);this.vs[this.av].sched=e;this.vs[this.av].schedId=d.id;e.setSizes=e.updateView;e.destructor=function(){};e.init(d.id,a,c);return this.vs[this._viewRestore()].sched};
